// This file is auto-generated by @hey-api/openapi-ts

export type ProblemDetail = {
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
    instance?: string;
    properties?: {
        [key: string]: unknown;
    };
};

export type EndrePeriodeDatoDto = {
    dato: string;
};

export type DeltakelseDto = {
    id?: string;
    deltaker: DeltakerDto;
    fraOgMed: string;
    tilOgMed?: string;
    søktTidspunkt?: string;
};

export type DeltakerDto = {
    id?: string;
    deltakerIdent: string;
};

export type DeltakelseUtmeldingDto = {
    utmeldingsdato: string;
};

export type DeltakelseInnmeldingDto = {
    deltakerIdent: string;
    startdato: string;
};

export type DeltakerPersonalia = {
    id?: string;
    deltakerIdent: string;
    navn: Navn;
    fødselsdato: string;
    /**
     * Diskresjonskoder som gjelder for deltakeren. Vil være tom hvis deltaker ikke har diskresjonskoder satt.
     */
    diskresjonskoder: Array<Diskresjonskode>;
    sisteMuligeInnmeldingsdato: string;
    førsteMuligeInnmeldingsdato: string;
};

export enum Diskresjonskode {
    KODE6 = 'KODE6',
    KODE7 = 'KODE7',
    SKJERMET = 'SKJERMET',
}

export type Navn = {
    fornavn: string;
    mellomnavn?: string;
    etternavn: string;
};

export type DeltakelseHistorikkDto = {
    tidspunkt: string;
    endringstype: Endringstype;
    revisjonstype: Revisjonstype;
    endring: string;
    aktør: string;
};

export enum Endringstype {
    DELTAKER_MELDT_INN = 'DELTAKER_MELDT_INN',
    DELTAKER_MELDT_UT = 'DELTAKER_MELDT_UT',
    ENDRET_STARTDATO = 'ENDRET_STARTDATO',
    ENDRET_SLUTTDATO = 'ENDRET_SLUTTDATO',
    DELTAKER_HAR_SØKT_YTELSE = 'DELTAKER_HAR_SØKT_YTELSE',
    UKJENT = 'UKJENT',
}

export enum Revisjonstype {
    OPPRETTET = 'OPPRETTET',
    ENDRET = 'ENDRET',
    SLETTET = 'SLETTET',
    UKJENT = 'UKJENT',
}

export type EndreStartdatoData = {
    body: EndrePeriodeDatoDto;
    path: {
        deltakelseId: string;
    };
    query?: never;
    url: '/veileder/register/deltakelse/{deltakelseId}/endre/startdato';
};

export type EndreStartdatoErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetail;
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type EndreStartdatoError = EndreStartdatoErrors[keyof EndreStartdatoErrors];

export type EndreStartdatoResponses = {
    /**
     * OK
     */
    200: DeltakelseDto;
};

export type EndreStartdatoResponse = EndreStartdatoResponses[keyof EndreStartdatoResponses];

export type EndreSluttdatoData = {
    body: EndrePeriodeDatoDto;
    path: {
        deltakelseId: string;
    };
    query?: never;
    url: '/veileder/register/deltakelse/{deltakelseId}/endre/sluttdato';
};

export type EndreSluttdatoErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetail;
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type EndreSluttdatoError = EndreSluttdatoErrors[keyof EndreSluttdatoErrors];

export type EndreSluttdatoResponses = {
    /**
     * OK
     */
    200: DeltakelseDto;
};

export type EndreSluttdatoResponse = EndreSluttdatoResponses[keyof EndreSluttdatoResponses];

export type MeldUtDeltakerData = {
    body: DeltakelseUtmeldingDto;
    path: {
        deltakelseId: string;
    };
    query?: never;
    url: '/veileder/register/deltakelse/{deltakelseId}/avslutt';
};

export type MeldUtDeltakerErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetail;
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type MeldUtDeltakerError = MeldUtDeltakerErrors[keyof MeldUtDeltakerErrors];

export type MeldUtDeltakerResponses = {
    /**
     * OK
     */
    200: DeltakelseDto;
};

export type MeldUtDeltakerResponse = MeldUtDeltakerResponses[keyof MeldUtDeltakerResponses];

export type MeldInnDeltakerData = {
    body: DeltakelseInnmeldingDto;
    path?: never;
    query?: never;
    url: '/veileder/register/deltaker/innmelding';
};

export type MeldInnDeltakerErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetail;
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type MeldInnDeltakerError = MeldInnDeltakerErrors[keyof MeldInnDeltakerErrors];

export type MeldInnDeltakerResponses = {
    /**
     * OK
     */
    200: DeltakelseDto;
};

export type MeldInnDeltakerResponse = MeldInnDeltakerResponses[keyof MeldInnDeltakerResponses];

export type HentDeltakerInfoGittDeltakerData = {
    body: DeltakerDto;
    path?: never;
    query?: never;
    url: '/oppslag/deltaker';
};

export type HentDeltakerInfoGittDeltakerErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetail;
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type HentDeltakerInfoGittDeltakerError =
    HentDeltakerInfoGittDeltakerErrors[keyof HentDeltakerInfoGittDeltakerErrors];

export type HentDeltakerInfoGittDeltakerResponses = {
    /**
     * OK
     */
    200: DeltakerPersonalia;
};

export type HentDeltakerInfoGittDeltakerResponse =
    HentDeltakerInfoGittDeltakerResponses[keyof HentDeltakerInfoGittDeltakerResponses];

export type HentAlleDeltakelserGittDeltakerIdData = {
    body?: never;
    path: {
        deltakerId: string;
    };
    query?: never;
    url: '/veileder/register/deltaker/{deltakerId}/deltakelser';
};

export type HentAlleDeltakelserGittDeltakerIdErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetail;
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type HentAlleDeltakelserGittDeltakerIdError =
    HentAlleDeltakelserGittDeltakerIdErrors[keyof HentAlleDeltakelserGittDeltakerIdErrors];

export type HentAlleDeltakelserGittDeltakerIdResponses = {
    /**
     * OK
     */
    200: Array<DeltakelseDto>;
};

export type HentAlleDeltakelserGittDeltakerIdResponse =
    HentAlleDeltakelserGittDeltakerIdResponses[keyof HentAlleDeltakelserGittDeltakerIdResponses];

export type DeltakelseHistorikkData = {
    body?: never;
    path: {
        deltakelseId: string;
    };
    query?: never;
    url: '/veileder/register/deltakelse/{deltakelseId}/historikk';
};

export type DeltakelseHistorikkErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetail;
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type DeltakelseHistorikkError = DeltakelseHistorikkErrors[keyof DeltakelseHistorikkErrors];

export type DeltakelseHistorikkResponses = {
    /**
     * OK
     */
    200: Array<DeltakelseHistorikkDto>;
};

export type DeltakelseHistorikkResponse = DeltakelseHistorikkResponses[keyof DeltakelseHistorikkResponses];

export type HentDeltakerInfoGittDeltakerIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/oppslag/deltaker/{id}';
};

export type HentDeltakerInfoGittDeltakerIdErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetail;
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type HentDeltakerInfoGittDeltakerIdError =
    HentDeltakerInfoGittDeltakerIdErrors[keyof HentDeltakerInfoGittDeltakerIdErrors];

export type HentDeltakerInfoGittDeltakerIdResponses = {
    /**
     * OK
     */
    200: DeltakerPersonalia;
};

export type HentDeltakerInfoGittDeltakerIdResponse =
    HentDeltakerInfoGittDeltakerIdResponses[keyof HentDeltakerInfoGittDeltakerIdResponses];

export type FjernFraProgramData = {
    body?: never;
    path: {
        deltakerId: string;
    };
    query?: never;
    url: '/veileder/register/deltaker/{deltakerId}/fjern';
};

export type FjernFraProgramErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetail;
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type FjernFraProgramError = FjernFraProgramErrors[keyof FjernFraProgramErrors];

export type FjernFraProgramResponses = {
    /**
     * No Content
     */
    204: void;
};

export type FjernFraProgramResponse = FjernFraProgramResponses[keyof FjernFraProgramResponses];

export type ClientOptions = {
    baseURL: 'https://ung-deltakelse-opplyser.intern.dev.nav.no' | (string & {});
};
