// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zProblemDetail = z.object({
    type: z.optional(z.url()),
    title: z.optional(z.string()),
    status: z.optional(
        z
            .int()
            .min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' })
            .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    ),
    detail: z.optional(z.string()),
    instance: z.optional(z.url()),
    properties: z.optional(z.record(z.string(), z.unknown())),
});

export const zEndrePeriodeDatoDto = z.object({
    dato: z.iso.date(),
});

export const zDeltakerDto = z.object({
    id: z.optional(z.uuid()),
    deltakerIdent: z.string(),
});

export const zDeltakelseDto = z.object({
    id: z.optional(z.uuid()),
    deltaker: zDeltakerDto,
    fraOgMed: z.iso.date(),
    tilOgMed: z.optional(z.iso.date()),
    erSlettet: z.boolean(),
    harOpphørsvedtak: z.boolean(),
    søktTidspunkt: z.optional(z.iso.datetime({ local: true })),
});

export const zDeltakelseUtmeldingDto = z.object({
    utmeldingsdato: z.iso.date(),
});

export const zDeltakelseInnmeldingDto = z.object({
    deltakerIdent: z.string(),
    startdato: z.iso.date(),
});

export const zDiskresjonskode = z.enum(['KODE6', 'KODE7', 'SKJERMET']);

export const zNavn = z.object({
    fornavn: z.string(),
    mellomnavn: z.optional(z.string()),
    etternavn: z.string(),
});

export const zDeltakerPersonalia = z.object({
    id: z.optional(z.uuid()),
    deltakerIdent: z.string(),
    navn: zNavn,
    fødselsdato: z.iso.date(),
    diskresjonskoder: z.array(zDiskresjonskode),
    førsteMuligeInnmeldingsdato: z.iso.date(),
    sisteMuligeInnmeldingsdato: z.iso.date(),
});

export const zEndringstype = z.enum([
    'DELTAKER_MELDT_INN',
    'DELTAKER_MELDT_UT',
    'ENDRET_STARTDATO',
    'ENDRET_SLUTTDATO',
    'DELTAKER_HAR_SØKT_YTELSE',
    'DELTAKELSE_FJERNET',
    'UKJENT',
]);

export const zRevisjonstype = z.enum(['OPPRETTET', 'ENDRET', 'SLETTET', 'UKJENT']);

export const zDeltakelseHistorikkDto = z.object({
    tidspunkt: z.iso.datetime({ local: true }),
    endringstype: zEndringstype,
    revisjonstype: zRevisjonstype,
    endring: z.string(),
    aktør: z.string(),
});

export const zEndreStartdatoData = z.object({
    body: zEndrePeriodeDatoDto,
    path: z.object({
        deltakelseId: z.uuid(),
    }),
    query: z.optional(z.never()),
});

/**
 * OK
 */
export const zEndreStartdatoResponse = zDeltakelseDto;

export const zEndreSluttdatoData = z.object({
    body: zEndrePeriodeDatoDto,
    path: z.object({
        deltakelseId: z.uuid(),
    }),
    query: z.optional(z.never()),
});

/**
 * OK
 */
export const zEndreSluttdatoResponse = zDeltakelseDto;

export const zMeldUtDeltakerData = z.object({
    body: zDeltakelseUtmeldingDto,
    path: z.object({
        deltakelseId: z.uuid(),
    }),
    query: z.optional(z.never()),
});

/**
 * OK
 */
export const zMeldUtDeltakerResponse = zDeltakelseDto;

export const zMeldInnDeltakerData = z.object({
    body: zDeltakelseInnmeldingDto,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});

/**
 * OK
 */
export const zMeldInnDeltakerResponse = zDeltakelseDto;

export const zHentDeltakerInfoGittDeltakerData = z.object({
    body: zDeltakerDto,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});

/**
 * OK
 */
export const zHentDeltakerInfoGittDeltakerResponse = zDeltakerPersonalia;

export const zHentAlleDeltakelserGittDeltakerIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        deltakerId: z.uuid(),
    }),
    query: z.optional(z.never()),
});

/**
 * OK
 */
export const zHentAlleDeltakelserGittDeltakerIdResponse = z.array(zDeltakelseDto);

export const zDeltakelseHistorikkData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        deltakelseId: z.uuid(),
    }),
    query: z.optional(z.never()),
});

/**
 * OK
 */
export const zDeltakelseHistorikkResponse = z.array(zDeltakelseHistorikkDto);

export const zHentDeltakerInfoGittDeltakerIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid(),
    }),
    query: z.optional(z.never()),
});

/**
 * OK
 */
export const zHentDeltakerInfoGittDeltakerIdResponse = zDeltakerPersonalia;

export const zFjernFraProgramData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        deltakerId: z.uuid(),
    }),
    query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zFjernFraProgramResponse = z.void();
