// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zProblemDetail = z.object({
    type: z.url().optional(),
    title: z.string().optional(),
    status: z
        .int()
        .min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' })
        .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
        .optional(),
    detail: z.string().optional(),
    instance: z.url().optional(),
    properties: z.record(z.string(), z.unknown()).optional(),
});

export const zEndrePeriodeDatoDto = z.object({
    dato: z.iso.date(),
});

export const zDeltakerDto = z.object({
    id: z.uuid().optional(),
    deltakerIdent: z.string(),
});

export const zDeltakelseDto = z.object({
    id: z.uuid().optional(),
    deltaker: zDeltakerDto,
    fraOgMed: z.iso.date(),
    tilOgMed: z.iso.date().optional(),
    erSlettet: z.boolean(),
    harOpphørsvedtak: z.boolean(),
    søktTidspunkt: z.iso.datetime({ local: true }).optional(),
});

export const zDeltakelseUtmeldingDto = z.object({
    utmeldingsdato: z.iso.date(),
});

export const zDeltakelseInnmeldingDto = z.object({
    deltakerIdent: z.string(),
    startdato: z.iso.date(),
});

export const zDiskresjonskode = z.enum(['KODE6', 'KODE7', 'SKJERMET']);

export const zNavn = z.object({
    fornavn: z.string(),
    mellomnavn: z.string().optional(),
    etternavn: z.string(),
});

export const zDeltakerPersonalia = z.object({
    id: z.uuid().optional(),
    deltakerIdent: z.string(),
    navn: zNavn,
    fødselsdato: z.iso.date(),
    diskresjonskoder: z.array(zDiskresjonskode),
    førsteMuligeInnmeldingsdato: z.iso.date(),
    sisteMuligeInnmeldingsdato: z.iso.date(),
});

export const zEndringstype = z.enum([
    'DELTAKER_MELDT_INN',
    'DELTAKER_MELDT_UT',
    'ENDRET_STARTDATO',
    'ENDRET_SLUTTDATO',
    'DELTAKER_HAR_SØKT_YTELSE',
    'DELTAKELSE_FJERNET',
    'UKJENT',
]);

export const zRevisjonstype = z.enum(['OPPRETTET', 'ENDRET', 'SLETTET', 'UKJENT']);

export const zDeltakelseHistorikkDto = z.object({
    tidspunkt: z.iso.datetime({ local: true }),
    endringstype: zEndringstype,
    revisjonstype: zRevisjonstype,
    endring: z.string(),
    aktør: z.string(),
});

export const zEndreStartdatoBody = zEndrePeriodeDatoDto;

export const zEndreStartdatoPath = z.object({
    deltakelseId: z.uuid(),
});

/**
 * OK
 */
export const zEndreStartdatoResponse = zDeltakelseDto;

export const zEndreSluttdatoBody = zEndrePeriodeDatoDto;

export const zEndreSluttdatoPath = z.object({
    deltakelseId: z.uuid(),
});

/**
 * OK
 */
export const zEndreSluttdatoResponse = zDeltakelseDto;

export const zMeldUtDeltakerBody = zDeltakelseUtmeldingDto;

export const zMeldUtDeltakerPath = z.object({
    deltakelseId: z.uuid(),
});

/**
 * OK
 */
export const zMeldUtDeltakerResponse = zDeltakelseDto;

export const zMeldInnDeltakerBody = zDeltakelseInnmeldingDto;

/**
 * OK
 */
export const zMeldInnDeltakerResponse = zDeltakelseDto;

export const zHentDeltakerInfoGittDeltakerBody = zDeltakerDto;

/**
 * OK
 */
export const zHentDeltakerInfoGittDeltakerResponse = zDeltakerPersonalia;

export const zHentAlleDeltakelserGittDeltakerIdPath = z.object({
    deltakerId: z.uuid(),
});

/**
 * OK
 */
export const zHentAlleDeltakelserGittDeltakerIdResponse = z.array(zDeltakelseDto);

export const zDeltakelseHistorikkPath = z.object({
    deltakelseId: z.uuid(),
});

/**
 * OK
 */
export const zDeltakelseHistorikkResponse = z.array(zDeltakelseHistorikkDto);

export const zHentDeltakerInfoGittDeltakerIdPath = z.object({
    id: z.uuid(),
});

/**
 * OK
 */
export const zHentDeltakerInfoGittDeltakerIdResponse = zDeltakerPersonalia;

export const zFjernFraProgramPath = z.object({
    deltakerId: z.uuid(),
});

/**
 * No Content
 */
export const zFjernFraProgramResponse = z.void();
