// This file is auto-generated by @hey-api/openapi-ts

import {
    type Options as ClientOptions,
    type TDataShape,
    type Client,
    formDataBodySerializer,
} from '@hey-api/client-axios';
import type {
    DeleteMellomlagringData,
    DeleteMellomlagringError,
    GetMellomlagringData,
    GetMellomlagringResponse,
    GetMellomlagringError,
    CreateMellomlagringData,
    CreateMellomlagringError,
    UpdateMellomlagringData,
    UpdateMellomlagringError,
    LagreVedleggData,
    LagreVedleggError,
    ValiderFriteksfeltData,
    ValiderFriteksfeltError,
    InnsendingData,
    InnsendingError,
    OppgavebekreftelseData,
    OppgavebekreftelseError,
    InntektrapporteringData,
    InntektrapporteringError,
    InnsendingPleiepengerSyktBarnSøknadData,
    InnsendingPleiepengerSyktBarnSøknadError,
    InnsendingEndringsmeldingData,
    InnsendingEndringsmeldingError,
    InnsendingPleiepengerILivetsSluttfaseSøknadData,
    InnsendingPleiepengerILivetsSluttfaseSøknadError,
    LagPdfData,
    LagPdfResponse,
    LagPdfError,
    InnsendingOpplæringspengerSøknadData,
    InnsendingOpplæringspengerSøknadError,
    InnsendingOmsorgspengerKroniskSyktBarnSøknadData,
    InnsendingOmsorgspengerKroniskSyktBarnSøknadError,
    InnsendingOmsorgspengerutbetalingSnfSøknadData,
    InnsendingOmsorgspengerutbetalingSnfSøknadError,
    InnsendingOmsorgspengerutbetalingArbeidstakerSøknadData,
    InnsendingOmsorgspengerutbetalingArbeidstakerSøknadError,
    InnsendingOmsorgspengerMidlertidigAleneSøknadData,
    InnsendingOmsorgspengerMidlertidigAleneSøknadError,
    InnsendingOmsorgsdagerAleneOmOmsorgenSøknadData,
    InnsendingOmsorgsdagerAleneOmOmsorgenSøknadError,
    InnsendingEttersendelseData,
    InnsendingEttersendelseError,
    SlettVedleggData,
    SlettVedleggResponse,
    SlettVedleggError,
    HentVedleggData,
    HentVedleggResponse,
    HentVedleggError,
    HentSøkerData,
    HentSøkerResponse,
    HentSøkerError,
    HentBarnData,
    HentBarnResponse,
    HentBarnError,
    HentArbeidsgivereData,
    HentArbeidsgivereResponse,
    HentArbeidsgivereError,
} from './types.gen';
import { client as _heyApiClient } from './client.gen';
import {
    zGetMellomlagringResponse,
    zLagPdfResponse,
    zSlettVedleggResponse,
    zHentVedleggResponse,
    zHentSøkerResponse,
    zHentBarnResponse,
    zHentArbeidsgivereResponse,
} from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<
    TData,
    ThrowOnError
> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class MellomlagringControllerService {
    public static deleteMellomlagring<ThrowOnError extends boolean = false>(
        options: Options<DeleteMellomlagringData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).delete<unknown, DeleteMellomlagringError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/mellomlagring/{ytelse}',
            ...options,
        });
    }

    public static getMellomlagring<ThrowOnError extends boolean = false>(
        options: Options<GetMellomlagringData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).get<GetMellomlagringResponse, GetMellomlagringError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            responseValidator: async (data) => {
                return await zGetMellomlagringResponse.parseAsync(data);
            },
            url: '/mellomlagring/{ytelse}',
            ...options,
        });
    }

    public static createMellomlagring<ThrowOnError extends boolean = false>(
        options: Options<CreateMellomlagringData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<unknown, CreateMellomlagringError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/mellomlagring/{ytelse}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
            },
        });
    }

    public static updateMellomlagring<ThrowOnError extends boolean = false>(
        options: Options<UpdateMellomlagringData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).put<unknown, UpdateMellomlagringError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/mellomlagring/{ytelse}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
            },
        });
    }
}

export class VedleggControllerService {
    public static lagreVedlegg<ThrowOnError extends boolean = false>(
        options?: Options<LagreVedleggData, ThrowOnError>,
    ) {
        return (options?.client ?? _heyApiClient).post<unknown, LagreVedleggError, ThrowOnError>({
            ...formDataBodySerializer,
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/vedlegg',
            ...options,
            headers: {
                'Content-Type': null,
                ...options?.headers,
            },
        });
    }

    public static slettVedlegg<ThrowOnError extends boolean = false>(options: Options<SlettVedleggData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<SlettVedleggResponse, SlettVedleggError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            responseValidator: async (data) => {
                return await zSlettVedleggResponse.parseAsync(data);
            },
            url: '/vedlegg/{vedleggId}',
            ...options,
        });
    }

    public static hentVedlegg<ThrowOnError extends boolean = false>(options: Options<HentVedleggData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<HentVedleggResponse, HentVedleggError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            responseValidator: async (data) => {
                return await zHentVedleggResponse.parseAsync(data);
            },
            url: '/vedlegg/{vedleggId}',
            ...options,
        });
    }
}

export class FeltValideringControllerService {
    public static validerFriteksfelt<ThrowOnError extends boolean = false>(
        options: Options<ValiderFriteksfeltData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<unknown, ValiderFriteksfeltError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/valider/friteksfelt',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
            },
        });
    }
}

export class UngdomsytelseControllerService {
    public static innsending<ThrowOnError extends boolean = false>(options: Options<InnsendingData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<unknown, InnsendingError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/ungdomsytelse/soknad/innsending',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
            },
        });
    }

    public static oppgavebekreftelse<ThrowOnError extends boolean = false>(
        options: Options<OppgavebekreftelseData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<unknown, OppgavebekreftelseError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/ungdomsytelse/oppgavebekreftelse/innsending',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
            },
        });
    }

    public static inntektrapportering<ThrowOnError extends boolean = false>(
        options: Options<InntektrapporteringData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<unknown, InntektrapporteringError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/ungdomsytelse/inntektsrapportering/innsending',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
            },
        });
    }
}

export class PleiepengerSyktBarnControllerService {
    public static innsendingPleiepengerSyktBarnSøknad<ThrowOnError extends boolean = false>(
        options: Options<InnsendingPleiepengerSyktBarnSøknadData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<unknown, InnsendingPleiepengerSyktBarnSøknadError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/pleiepenger-sykt-barn/innsending',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
            },
        });
    }
}

export class EndringsmeldingControllerService {
    public static innsendingEndringsmelding<ThrowOnError extends boolean = false>(
        options: Options<InnsendingEndringsmeldingData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<unknown, InnsendingEndringsmeldingError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/pleiepenger-sykt-barn/endringsmelding/innsending',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
            },
        });
    }
}

export class PleiepengerLivetsSluttfaseControllerService {
    public static innsendingPleiepengerILivetsSluttfaseSøknad<ThrowOnError extends boolean = false>(
        options: Options<InnsendingPleiepengerILivetsSluttfaseSøknadData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            unknown,
            InnsendingPleiepengerILivetsSluttfaseSøknadError,
            ThrowOnError
        >({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/pleiepenger-livets-sluttfase/innsending',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
            },
        });
    }
}

export class PdfControllerService {
    public static lagPdf<ThrowOnError extends boolean = false>(options: Options<LagPdfData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<LagPdfResponse, LagPdfError, ThrowOnError>({
            responseType: 'blob',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            responseValidator: async (data) => {
                return await zLagPdfResponse.parseAsync(data);
            },
            url: '/pdf',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
            },
        });
    }
}

export class OpplÆringspengerSØknadControllerService {
    public static innsendingOpplæringspengerSøknad<ThrowOnError extends boolean = false>(
        options: Options<InnsendingOpplæringspengerSøknadData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<unknown, InnsendingOpplæringspengerSøknadError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/opplaringspenger/innsending',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
            },
        });
    }
}

export class OmsorgspengerUtvidetRettControllerService {
    public static innsendingOmsorgspengerKroniskSyktBarnSøknad<ThrowOnError extends boolean = false>(
        options: Options<InnsendingOmsorgspengerKroniskSyktBarnSøknadData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            unknown,
            InnsendingOmsorgspengerKroniskSyktBarnSøknadError,
            ThrowOnError
        >({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/omsorgspenger-utvidet-rett/innsending',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
            },
        });
    }
}

export class OmsorgspengerUtbetalingSnfControllerService {
    public static innsendingOmsorgspengerutbetalingSnfSøknad<ThrowOnError extends boolean = false>(
        options: Options<InnsendingOmsorgspengerutbetalingSnfSøknadData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            unknown,
            InnsendingOmsorgspengerutbetalingSnfSøknadError,
            ThrowOnError
        >({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/omsorgspenger-utbetaling-snf/innsending',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
            },
        });
    }
}

export class OmsorgspengerUtbetalingArbeidstakerControllerService {
    public static innsendingOmsorgspengerutbetalingArbeidstakerSøknad<ThrowOnError extends boolean = false>(
        options: Options<InnsendingOmsorgspengerutbetalingArbeidstakerSøknadData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            unknown,
            InnsendingOmsorgspengerutbetalingArbeidstakerSøknadError,
            ThrowOnError
        >({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/omsorgspenger-utbetaling-arbeidstaker/innsending',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
            },
        });
    }
}

export class OmsorgspengerMidlertidigAleneControllerService {
    public static innsendingOmsorgspengerMidlertidigAleneSøknad<ThrowOnError extends boolean = false>(
        options: Options<InnsendingOmsorgspengerMidlertidigAleneSøknadData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            unknown,
            InnsendingOmsorgspengerMidlertidigAleneSøknadError,
            ThrowOnError
        >({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/omsorgspenger-midlertidig-alene/innsending',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
            },
        });
    }
}

export class OmsorgsdagerAleneomsorgControllerService {
    public static innsendingOmsorgsdagerAleneOmOmsorgenSøknad<ThrowOnError extends boolean = false>(
        options: Options<InnsendingOmsorgsdagerAleneOmOmsorgenSøknadData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            unknown,
            InnsendingOmsorgsdagerAleneOmOmsorgenSøknadError,
            ThrowOnError
        >({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/omsorgsdager-aleneomsorg/innsending',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
            },
        });
    }
}

export class EttersendingControllerService {
    public static innsendingEttersendelse<ThrowOnError extends boolean = false>(
        options: Options<InnsendingEttersendelseData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<unknown, InnsendingEttersendelseError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/ettersending/innsending',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
            },
        });
    }
}

export class SØkerControllerService {
    public static hentSøker<ThrowOnError extends boolean = false>(options?: Options<HentSøkerData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<HentSøkerResponse, HentSøkerError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            responseValidator: async (data) => {
                return await zHentSøkerResponse.parseAsync(data);
            },
            url: '/oppslag/soker',
            ...options,
        });
    }
}

export class BarnControllerService {
    public static hentBarn<ThrowOnError extends boolean = false>(options?: Options<HentBarnData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<HentBarnResponse, HentBarnError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            responseValidator: async (data) => {
                return await zHentBarnResponse.parseAsync(data);
            },
            url: '/oppslag/barn',
            ...options,
        });
    }
}

export class ArbeidsgivereControllerService {
    public static hentArbeidsgivere<ThrowOnError extends boolean = false>(
        options: Options<HentArbeidsgivereData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).get<HentArbeidsgivereResponse, HentArbeidsgivereError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            responseValidator: async (data) => {
                return await zHentArbeidsgivereResponse.parseAsync(data);
            },
            url: '/oppslag/arbeidsgiver',
            ...options,
        });
    }
}
