// This file is auto-generated by @hey-api/openapi-ts

import {
    type Options as ClientOptions,
    type TDataShape,
    type Client,
    formDataBodySerializer,
} from '@hey-api/client-axios';
import type {
    DeleteMellomlagringData,
    DeleteMellomlagringResponses,
    DeleteMellomlagringErrors,
    GetMellomlagringData,
    GetMellomlagringResponses,
    GetMellomlagringErrors,
    CreateMellomlagringData,
    CreateMellomlagringResponses,
    CreateMellomlagringErrors,
    UpdateMellomlagringData,
    UpdateMellomlagringResponses,
    UpdateMellomlagringErrors,
    LagreVedleggData,
    LagreVedleggResponses,
    LagreVedleggErrors,
    ValiderFriteksfeltData,
    ValiderFriteksfeltResponses,
    ValiderFriteksfeltErrors,
    InnsendingUngdomsytelsesøknadData,
    InnsendingUngdomsytelsesøknadResponses,
    InnsendingUngdomsytelsesøknadErrors,
    OppgavebekreftelseData,
    OppgavebekreftelseResponses,
    OppgavebekreftelseErrors,
    InntektrapporteringData,
    InntektrapporteringResponses,
    InntektrapporteringErrors,
    InnsendingPleiepengerSyktBarnSøknadData,
    InnsendingPleiepengerSyktBarnSøknadResponses,
    InnsendingPleiepengerSyktBarnSøknadErrors,
    InnsendingEndringsmeldingData,
    InnsendingEndringsmeldingResponses,
    InnsendingEndringsmeldingErrors,
    InnsendingPleiepengerILivetsSluttfaseSøknadData,
    InnsendingPleiepengerILivetsSluttfaseSøknadResponses,
    InnsendingPleiepengerILivetsSluttfaseSøknadErrors,
    LagPdfData,
    LagPdfResponses,
    LagPdfErrors,
    InnsendingOpplæringspengerSøknadData,
    InnsendingOpplæringspengerSøknadResponses,
    InnsendingOpplæringspengerSøknadErrors,
    InnsendingOmsorgspengerKroniskSyktBarnSøknadData,
    InnsendingOmsorgspengerKroniskSyktBarnSøknadResponses,
    InnsendingOmsorgspengerKroniskSyktBarnSøknadErrors,
    InnsendingOmsorgspengerutbetalingSnfSøknadData,
    InnsendingOmsorgspengerutbetalingSnfSøknadResponses,
    InnsendingOmsorgspengerutbetalingSnfSøknadErrors,
    InnsendingOmsorgspengerutbetalingArbeidstakerSøknadData,
    InnsendingOmsorgspengerutbetalingArbeidstakerSøknadResponses,
    InnsendingOmsorgspengerutbetalingArbeidstakerSøknadErrors,
    InnsendingOmsorgspengerMidlertidigAleneSøknadData,
    InnsendingOmsorgspengerMidlertidigAleneSøknadResponses,
    InnsendingOmsorgspengerMidlertidigAleneSøknadErrors,
    InnsendingOmsorgsdagerAleneOmOmsorgenSøknadData,
    InnsendingOmsorgsdagerAleneOmOmsorgenSøknadResponses,
    InnsendingOmsorgsdagerAleneOmOmsorgenSøknadErrors,
    InnsendingEttersendelseData,
    InnsendingEttersendelseResponses,
    InnsendingEttersendelseErrors,
    SlettVedleggData,
    SlettVedleggResponses,
    SlettVedleggErrors,
    HentVedleggData,
    HentVedleggResponses,
    HentVedleggErrors,
    HentSøkerData,
    HentSøkerResponses,
    HentSøkerErrors,
    HentBarnData,
    HentBarnResponses,
    HentBarnErrors,
    HentArbeidsgivereData,
    HentArbeidsgivereResponses,
    HentArbeidsgivereErrors,
} from './types.gen';
import { client as _heyApiClient } from './client.gen';
import {
    zGetMellomlagringResponse,
    zLagPdfResponse,
    zSlettVedleggResponse,
    zHentVedleggResponse,
    zHentSøkerResponse,
    zHentBarnResponse,
    zHentArbeidsgivereResponse,
} from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<
    TData,
    ThrowOnError
> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class MellomlagringControllerService {
    public static deleteMellomlagring<ThrowOnError extends boolean = true>(
        options: Options<DeleteMellomlagringData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).delete<
            DeleteMellomlagringResponses,
            DeleteMellomlagringErrors,
            ThrowOnError
        >({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/mellomlagring/{ytelse}',
            ...options,
        });
    }

    public static getMellomlagring<ThrowOnError extends boolean = true>(
        options: Options<GetMellomlagringData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).get<GetMellomlagringResponses, GetMellomlagringErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            responseValidator: async (data) => {
                return await zGetMellomlagringResponse.parseAsync(data);
            },
            url: '/mellomlagring/{ytelse}',
            ...options,
        });
    }

    public static createMellomlagring<ThrowOnError extends boolean = true>(
        options: Options<CreateMellomlagringData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            CreateMellomlagringResponses,
            CreateMellomlagringErrors,
            ThrowOnError
        >({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/mellomlagring/{ytelse}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }

    public static updateMellomlagring<ThrowOnError extends boolean = true>(
        options: Options<UpdateMellomlagringData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).put<
            UpdateMellomlagringResponses,
            UpdateMellomlagringErrors,
            ThrowOnError
        >({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/mellomlagring/{ytelse}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }
}

export class VedleggControllerService {
    public static lagreVedlegg<ThrowOnError extends boolean = true>(options?: Options<LagreVedleggData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<LagreVedleggResponses, LagreVedleggErrors, ThrowOnError>({
            ...formDataBodySerializer,
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/vedlegg',
            ...options,
            headers: {
                'Content-Type': null,
                ...options?.headers,
            },
        });
    }

    public static slettVedlegg<ThrowOnError extends boolean = true>(options: Options<SlettVedleggData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<SlettVedleggResponses, SlettVedleggErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            responseValidator: async (data) => {
                return await zSlettVedleggResponse.parseAsync(data);
            },
            url: '/vedlegg/{vedleggId}',
            ...options,
        });
    }

    public static hentVedlegg<ThrowOnError extends boolean = true>(options: Options<HentVedleggData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<HentVedleggResponses, HentVedleggErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            responseValidator: async (data) => {
                return await zHentVedleggResponse.parseAsync(data);
            },
            url: '/vedlegg/{vedleggId}',
            ...options,
        });
    }
}

export class FeltValideringControllerService {
    public static validerFriteksfelt<ThrowOnError extends boolean = true>(
        options: Options<ValiderFriteksfeltData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            ValiderFriteksfeltResponses,
            ValiderFriteksfeltErrors,
            ThrowOnError
        >({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/valider/friteksfelt',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }
}

export class UngdomsytelseControllerService {
    public static innsendingUngdomsytelsesøknad<ThrowOnError extends boolean = true>(
        options: Options<InnsendingUngdomsytelsesøknadData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            InnsendingUngdomsytelsesøknadResponses,
            InnsendingUngdomsytelsesøknadErrors,
            ThrowOnError
        >({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/ungdomsytelse/soknad/innsending',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }

    public static oppgavebekreftelse<ThrowOnError extends boolean = true>(
        options: Options<OppgavebekreftelseData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            OppgavebekreftelseResponses,
            OppgavebekreftelseErrors,
            ThrowOnError
        >({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/ungdomsytelse/oppgavebekreftelse/innsending',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }

    public static inntektrapportering<ThrowOnError extends boolean = true>(
        options: Options<InntektrapporteringData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            InntektrapporteringResponses,
            InntektrapporteringErrors,
            ThrowOnError
        >({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/ungdomsytelse/inntektsrapportering/innsending',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }
}

export class PleiepengerSyktBarnControllerService {
    public static innsendingPleiepengerSyktBarnSøknad<ThrowOnError extends boolean = true>(
        options: Options<InnsendingPleiepengerSyktBarnSøknadData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            InnsendingPleiepengerSyktBarnSøknadResponses,
            InnsendingPleiepengerSyktBarnSøknadErrors,
            ThrowOnError
        >({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/pleiepenger-sykt-barn/innsending',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }
}

export class EndringsmeldingControllerService {
    public static innsendingEndringsmelding<ThrowOnError extends boolean = true>(
        options: Options<InnsendingEndringsmeldingData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            InnsendingEndringsmeldingResponses,
            InnsendingEndringsmeldingErrors,
            ThrowOnError
        >({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/pleiepenger-sykt-barn/endringsmelding/innsending',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }
}

export class PleiepengerLivetsSluttfaseControllerService {
    public static innsendingPleiepengerILivetsSluttfaseSøknad<ThrowOnError extends boolean = true>(
        options: Options<InnsendingPleiepengerILivetsSluttfaseSøknadData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            InnsendingPleiepengerILivetsSluttfaseSøknadResponses,
            InnsendingPleiepengerILivetsSluttfaseSøknadErrors,
            ThrowOnError
        >({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/pleiepenger-livets-sluttfase/innsending',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }
}

export class PdfControllerService {
    public static lagPdf<ThrowOnError extends boolean = true>(options: Options<LagPdfData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<LagPdfResponses, LagPdfErrors, ThrowOnError>({
            responseType: 'blob',
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            responseValidator: async (data) => {
                return await zLagPdfResponse.parseAsync(data);
            },
            url: '/pdf',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }
}

export class OpplÆringspengerSØknadControllerService {
    public static innsendingOpplæringspengerSøknad<ThrowOnError extends boolean = true>(
        options: Options<InnsendingOpplæringspengerSøknadData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            InnsendingOpplæringspengerSøknadResponses,
            InnsendingOpplæringspengerSøknadErrors,
            ThrowOnError
        >({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/opplaringspenger/innsending',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }
}

export class OmsorgspengerUtvidetRettControllerService {
    public static innsendingOmsorgspengerKroniskSyktBarnSøknad<ThrowOnError extends boolean = true>(
        options: Options<InnsendingOmsorgspengerKroniskSyktBarnSøknadData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            InnsendingOmsorgspengerKroniskSyktBarnSøknadResponses,
            InnsendingOmsorgspengerKroniskSyktBarnSøknadErrors,
            ThrowOnError
        >({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/omsorgspenger-utvidet-rett/innsending',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }
}

export class OmsorgspengerUtbetalingSnfControllerService {
    public static innsendingOmsorgspengerutbetalingSnfSøknad<ThrowOnError extends boolean = true>(
        options: Options<InnsendingOmsorgspengerutbetalingSnfSøknadData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            InnsendingOmsorgspengerutbetalingSnfSøknadResponses,
            InnsendingOmsorgspengerutbetalingSnfSøknadErrors,
            ThrowOnError
        >({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/omsorgspenger-utbetaling-snf/innsending',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }
}

export class OmsorgspengerUtbetalingArbeidstakerControllerService {
    public static innsendingOmsorgspengerutbetalingArbeidstakerSøknad<ThrowOnError extends boolean = true>(
        options: Options<InnsendingOmsorgspengerutbetalingArbeidstakerSøknadData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            InnsendingOmsorgspengerutbetalingArbeidstakerSøknadResponses,
            InnsendingOmsorgspengerutbetalingArbeidstakerSøknadErrors,
            ThrowOnError
        >({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/omsorgspenger-utbetaling-arbeidstaker/innsending',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }
}

export class OmsorgspengerMidlertidigAleneControllerService {
    public static innsendingOmsorgspengerMidlertidigAleneSøknad<ThrowOnError extends boolean = true>(
        options: Options<InnsendingOmsorgspengerMidlertidigAleneSøknadData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            InnsendingOmsorgspengerMidlertidigAleneSøknadResponses,
            InnsendingOmsorgspengerMidlertidigAleneSøknadErrors,
            ThrowOnError
        >({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/omsorgspenger-midlertidig-alene/innsending',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }
}

export class OmsorgsdagerAleneomsorgControllerService {
    public static innsendingOmsorgsdagerAleneOmOmsorgenSøknad<ThrowOnError extends boolean = true>(
        options: Options<InnsendingOmsorgsdagerAleneOmOmsorgenSøknadData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            InnsendingOmsorgsdagerAleneOmOmsorgenSøknadResponses,
            InnsendingOmsorgsdagerAleneOmOmsorgenSøknadErrors,
            ThrowOnError
        >({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/omsorgsdager-aleneomsorg/innsending',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }
}

export class EttersendingControllerService {
    public static innsendingEttersendelse<ThrowOnError extends boolean = true>(
        options: Options<InnsendingEttersendelseData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            InnsendingEttersendelseResponses,
            InnsendingEttersendelseErrors,
            ThrowOnError
        >({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/ettersending/innsending',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }
}

export class SØkerControllerService {
    public static hentSøker<ThrowOnError extends boolean = true>(options?: Options<HentSøkerData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<HentSøkerResponses, HentSøkerErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            responseValidator: async (data) => {
                return await zHentSøkerResponse.parseAsync(data);
            },
            url: '/oppslag/soker',
            ...options,
        });
    }
}

export class BarnControllerService {
    public static hentBarn<ThrowOnError extends boolean = true>(options?: Options<HentBarnData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<HentBarnResponses, HentBarnErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            responseValidator: async (data) => {
                return await zHentBarnResponse.parseAsync(data);
            },
            url: '/oppslag/barn',
            ...options,
        });
    }
}

export class ArbeidsgivereControllerService {
    public static hentArbeidsgivere<ThrowOnError extends boolean = true>(
        options: Options<HentArbeidsgivereData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).get<HentArbeidsgivereResponses, HentArbeidsgivereErrors, ThrowOnError>(
            {
                security: [
                    {
                        scheme: 'bearer',
                        type: 'http',
                    },
                ],
                responseValidator: async (data) => {
                    return await zHentArbeidsgivereResponse.parseAsync(data);
                },
                url: '/oppslag/arbeidsgiver',
                ...options,
            },
        );
    }
}
