compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  navikt:
    npmAlwaysAuth: true
    # npmAuthToken: ${PACKAGES_AUTH_TOKEN}
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.5.0.cjs
