compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

npmScopes:
  navikt:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.10.3.cjs

# 7 dager: 10080
# 4 dager: 5760
# 2 dager: 2880
# 1 dag: 1440

npmMinimalAgeGate: 5760

npmPreapprovedPackages:
  - '@navikt/*'
  - 'react@19.2.1'
  - 'react-dom@19.2.1'
  - 'react-router-dom@7.12.0'
  - 'react-router@7.12.0'
  - 'axios@1.13.5'
  - "@isaacs/brace-expansion@5.0.1"
