packages:
  - "apps/*"
  - "apps-intern/*"
  - "packages/*"
  - "server"
  - "server-ungdomsytelse-veileder"

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@navikt/nav-dekoratoren-moduler@4.2.0'
