packages:
  - "apps/*"
  - "apps-intern/*"
  - "packages/*"
  - "server"
  - "server-ungdomsytelse-veileder"

allowBuilds:
  '@parcel/watcher': set this to true or false
  '@sentry/cli': set this to true or false
  '@swc/core': set this to true or false
  core-js-pure: set this to true or false
  esbuild: set this to true or false
  msw: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@navikt/nav-dekoratoren-moduler@4.2.0'
  - 'react-router-dom@7.16.0'
  - 'react-router@7.16.0'
