// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
    HentAlleMineDeltakelserData,
    HentAlleMineDeltakelserErrors,
    HentAlleMineDeltakelserResponses,
    HentAlleMineDeltakelserV2Data,
    HentAlleMineDeltakelserV2Errors,
    HentAlleMineDeltakelserV2Responses,
    HentKontonummerData,
    HentKontonummerErrors,
    HentKontonummerResponses,
    MarkerDeltakelseSomSøktData,
    MarkerDeltakelseSomSøktErrors,
    MarkerDeltakelseSomSøktResponses,
    MarkerDeltakelseSomSøktV2Data,
    MarkerDeltakelseSomSøktV2Errors,
    MarkerDeltakelseSomSøktV2Responses,
} from './types.gen';
import {
    zHentAlleMineDeltakelserResponse,
    zHentAlleMineDeltakelserV2Response,
    zHentKontonummerResponse,
    zMarkerDeltakelseSomSøktPath,
    zMarkerDeltakelseSomSøktResponse,
    zMarkerDeltakelseSomSøktV2Path,
    zMarkerDeltakelseSomSøktV2Response,
} from './zod.gen';

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
    TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Deltakelse {
    /**
     * Henter alle deltakelser for en deltaker i ungdomsprogrammet (deprecated – bruk /hent/alle/v2)
     *
     * @deprecated
     */
    public static hentAlleMineDeltakelser<ThrowOnError extends boolean = true>(
        options?: Options<HentAlleMineDeltakelserData, ThrowOnError>,
    ) {
        return (options?.client ?? client).get<
            HentAlleMineDeltakelserResponses,
            HentAlleMineDeltakelserErrors,
            ThrowOnError
        >({
            requestValidator: async (data) =>
                await z
                    .object({
                        body: z.never().optional(),
                        path: z.never().optional(),
                        query: z.never().optional(),
                    })
                    .parseAsync(data),
            responseType: 'json',
            responseValidator: async (data) => await zHentAlleMineDeltakelserResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { scheme: 'bearer', type: 'http' },
                { scheme: 'bearer', type: 'http' },
            ],
            url: '/deltakelse/register/hent/alle',
            ...options,
        });
    }

    /**
     * Henter alle deltakelser for en deltaker i ungdomsprogrammet
     */
    public static hentAlleMineDeltakelserV2<ThrowOnError extends boolean = true>(
        options?: Options<HentAlleMineDeltakelserV2Data, ThrowOnError>,
    ) {
        return (options?.client ?? client).get<
            HentAlleMineDeltakelserV2Responses,
            HentAlleMineDeltakelserV2Errors,
            ThrowOnError
        >({
            requestValidator: async (data) =>
                await z
                    .object({
                        body: z.never().optional(),
                        path: z.never().optional(),
                        query: z.never().optional(),
                    })
                    .parseAsync(data),
            responseType: 'json',
            responseValidator: async (data) => await zHentAlleMineDeltakelserV2Response.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { scheme: 'bearer', type: 'http' },
                { scheme: 'bearer', type: 'http' },
            ],
            url: '/deltakelse/register/hent/alle/v2',
            ...options,
        });
    }

    /**
     * Markerer at deltakelsen er søkt om (deprecated – bruk /{id}/marker-har-sokt/v2)
     *
     * @deprecated
     */
    public static markerDeltakelseSomSøkt<ThrowOnError extends boolean = true>(
        options: Options<MarkerDeltakelseSomSøktData, ThrowOnError>,
    ) {
        return (options.client ?? client).put<
            MarkerDeltakelseSomSøktResponses,
            MarkerDeltakelseSomSøktErrors,
            ThrowOnError
        >({
            requestValidator: async (data) =>
                await z
                    .object({
                        body: z.never().optional(),
                        path: zMarkerDeltakelseSomSøktPath,
                        query: z.never().optional(),
                    })
                    .parseAsync(data),
            responseType: 'json',
            responseValidator: async (data) => await zMarkerDeltakelseSomSøktResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { scheme: 'bearer', type: 'http' },
                { scheme: 'bearer', type: 'http' },
            ],
            url: '/deltakelse/register/{id}/marker-har-sokt',
            ...options,
        });
    }

    /**
     * Markerer at deltakelsen er søkt om
     */
    public static markerDeltakelseSomSøktV2<ThrowOnError extends boolean = true>(
        options: Options<MarkerDeltakelseSomSøktV2Data, ThrowOnError>,
    ) {
        return (options.client ?? client).put<
            MarkerDeltakelseSomSøktV2Responses,
            MarkerDeltakelseSomSøktV2Errors,
            ThrowOnError
        >({
            requestValidator: async (data) =>
                await z
                    .object({
                        body: z.never().optional(),
                        path: zMarkerDeltakelseSomSøktV2Path,
                        query: z.never().optional(),
                    })
                    .parseAsync(data),
            responseType: 'json',
            responseValidator: async (data) => await zMarkerDeltakelseSomSøktV2Response.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { scheme: 'bearer', type: 'http' },
                { scheme: 'bearer', type: 'http' },
            ],
            url: '/deltakelse/register/{id}/marker-har-sokt/v2',
            ...options,
        });
    }
}

export class Deltaker {
    /**
     * Henter kontonummer for en deltaker i ungdomsprogrammet
     */
    public static hentKontonummer<ThrowOnError extends boolean = true>(
        options?: Options<HentKontonummerData, ThrowOnError>,
    ) {
        return (options?.client ?? client).get<HentKontonummerResponses, HentKontonummerErrors, ThrowOnError>({
            requestValidator: async (data) =>
                await z
                    .object({
                        body: z.never().optional(),
                        path: z.never().optional(),
                        query: z.never().optional(),
                    })
                    .parseAsync(data),
            responseType: 'json',
            responseValidator: async (data) => await zHentKontonummerResponse.parseAsync(data),
            security: [
                { scheme: 'bearer', type: 'http' },
                { scheme: 'bearer', type: 'http' },
                { scheme: 'bearer', type: 'http' },
            ],
            url: '/deltaker/hent-kontonummer',
            ...options,
        });
    }
}
