// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string & {};
};

export type ProblemDetail = {
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
    instance?: string;
    properties?: {
        [key: string]: unknown;
    };
};

export type DeltakelseDto = {
    id?: string;
    deltaker: DeltakerDto;
    fraOgMed: string;
    tilOgMed?: string;
    erSlettet: boolean;
    harOpphørsvedtak: boolean;
    søktTidspunkt?: string;
};

export type DeltakelseKomposittDto = {
    id?: string;
    deltaker: DeltakerDto;
    fraOgMed: string;
    tilOgMed?: string;
    erSlettet: boolean;
    harOpphørsvedtak: boolean;
    søktTidspunkt?: string;
    oppgaver: unknown[];
};

export type DeltakerDto = {
    id?: string;
    deltakerIdent: string;
};

export type KontonummerDto = {
    harKontonummer: boolean;
    kontonummer?: string;
};

export type MarkerDeltakelseSomSøktData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/deltakelse/register/{id}/marker-har-sokt';
};

export type MarkerDeltakelseSomSøktErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetail;
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type MarkerDeltakelseSomSøktError = MarkerDeltakelseSomSøktErrors[keyof MarkerDeltakelseSomSøktErrors];

export type MarkerDeltakelseSomSøktResponses = {
    /**
     * OK
     */
    200: DeltakelseKomposittDto;
};

export type MarkerDeltakelseSomSøktResponse = MarkerDeltakelseSomSøktResponses[keyof MarkerDeltakelseSomSøktResponses];

export type MarkerDeltakelseSomSøktV2Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/deltakelse/register/{id}/marker-har-sokt/v2';
};

export type MarkerDeltakelseSomSøktV2Errors = {
    /**
     * Unauthorized
     */
    401: ProblemDetail;
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type MarkerDeltakelseSomSøktV2Error = MarkerDeltakelseSomSøktV2Errors[keyof MarkerDeltakelseSomSøktV2Errors];

export type MarkerDeltakelseSomSøktV2Responses = {
    /**
     * OK
     */
    200: DeltakelseDto;
};

export type MarkerDeltakelseSomSøktV2Response =
    MarkerDeltakelseSomSøktV2Responses[keyof MarkerDeltakelseSomSøktV2Responses];

export type HentKontonummerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/deltaker/hent-kontonummer';
};

export type HentKontonummerErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetail;
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type HentKontonummerError = HentKontonummerErrors[keyof HentKontonummerErrors];

export type HentKontonummerResponses = {
    /**
     * OK
     */
    200: KontonummerDto;
};

export type HentKontonummerResponse = HentKontonummerResponses[keyof HentKontonummerResponses];

export type HentAlleMineDeltakelserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/deltakelse/register/hent/alle';
};

export type HentAlleMineDeltakelserErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetail;
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type HentAlleMineDeltakelserError = HentAlleMineDeltakelserErrors[keyof HentAlleMineDeltakelserErrors];

export type HentAlleMineDeltakelserResponses = {
    /**
     * OK
     */
    200: DeltakelseKomposittDto[];
};

export type HentAlleMineDeltakelserResponse = HentAlleMineDeltakelserResponses[keyof HentAlleMineDeltakelserResponses];

export type HentAlleMineDeltakelserV2Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/deltakelse/register/hent/alle/v2';
};

export type HentAlleMineDeltakelserV2Errors = {
    /**
     * Unauthorized
     */
    401: ProblemDetail;
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type HentAlleMineDeltakelserV2Error = HentAlleMineDeltakelserV2Errors[keyof HentAlleMineDeltakelserV2Errors];

export type HentAlleMineDeltakelserV2Responses = {
    /**
     * OK
     */
    200: DeltakelseDto[];
};

export type HentAlleMineDeltakelserV2Response =
    HentAlleMineDeltakelserV2Responses[keyof HentAlleMineDeltakelserV2Responses];
