// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zProblemDetail = z.object({
    type: z.optional(z.url()),
    title: z.optional(z.string()),
    status: z.optional(z.int()),
    detail: z.optional(z.string()),
    instance: z.optional(z.url()),
    properties: z.optional(z.record(z.string(), z.unknown())),
});

export const zArbeidOgFrilansRegisterInntektDto = z.object({
    inntekt: z.int(),
    arbeidsgiver: z.string(),
    arbeidsgiverNavn: z.optional(z.string()),
});

export const zBekreftelseDto = z.object({
    harUttalelse: z.boolean(),
    uttalelseFraBruker: z.optional(z.string()),
});

export const zDeltakerDto = z.object({
    id: z.optional(z.uuid()),
    deltakerIdent: z.string(),
});

export const zOppgaveStatus = z.enum(['LØST', 'ULØST', 'AVBRUTT', 'UTLØPT', 'LUKKET']);

export const zOppgavetype = z.enum([
    'BEKREFT_ENDRET_STARTDATO',
    'BEKREFT_ENDRET_SLUTTDATO',
    'BEKREFT_AVVIK_REGISTERINNTEKT',
    'RAPPORTER_INNTEKT',
    'SØK_YTELSE',
]);

export const zOppgavetypeDataDto = z.unknown();

export const zEndretSluttdatoDataDto = zOppgavetypeDataDto.and(
    z.object({
        nySluttdato: z.iso.date(),
        forrigeSluttdato: z.optional(z.iso.date()),
    }),
);

export const zEndretStartdatoDataDto = zOppgavetypeDataDto.and(
    z.object({
        nyStartdato: z.iso.date(),
        forrigeStartdato: z.iso.date(),
    }),
);

export const zRapportertInntektPeriodeinfoDto = z.object({
    fraOgMed: z.iso.date(),
    tilOgMed: z.iso.date(),
    arbeidstakerOgFrilansInntekt: z.optional(z.number()),
});

export const zInntektsrapporteringOppgavetypeDataDto = zOppgavetypeDataDto.and(
    z.object({
        fraOgMed: z.iso.date(),
        tilOgMed: z.iso.date(),
        rapportertInntekt: z.optional(zRapportertInntektPeriodeinfoDto),
    }),
);

export const zSøkYtelseOppgavetypeDataDto = zOppgavetypeDataDto.and(
    z.object({
        fomDato: z.iso.date(),
    }),
);

export const zYtelseType = z.enum([
    'SYKEPENGER',
    'OMSORGSPENGER',
    'PLEIEPENGER_SYKT_BARN',
    'PLEIEPENGER_LIVETS_SLUTTFASE',
    'OPPLAERINGSPENGER',
]);

export const zYtelseRegisterInntektDto = z.object({
    inntekt: z.int(),
    ytelsetype: zYtelseType,
});

export const zRegisterinntektDto = z.object({
    arbeidOgFrilansInntekter: z.array(zArbeidOgFrilansRegisterInntektDto),
    ytelseInntekter: z.array(zYtelseRegisterInntektDto),
    totalInntektArbeidOgFrilans: z.int(),
    totalInntektYtelse: z.int(),
    totalInntekt: z.int(),
});

export const zKontrollerRegisterinntektOppgavetypeDataDto = zOppgavetypeDataDto.and(
    z.object({
        fraOgMed: z.iso.date(),
        tilOgMed: z.iso.date(),
        registerinntekt: zRegisterinntektDto,
        gjelderSisteMåned: z.boolean(),
    }),
);

export const zOppgaveDto = z.object({
    oppgaveReferanse: z.uuid(),
    oppgavetype: zOppgavetype,
    oppgavetypeData: z.union([
        zEndretSluttdatoDataDto,
        zEndretStartdatoDataDto,
        zInntektsrapporteringOppgavetypeDataDto,
        zKontrollerRegisterinntektOppgavetypeDataDto,
        zSøkYtelseOppgavetypeDataDto,
    ]),
    bekreftelse: z.optional(zBekreftelseDto),
    status: zOppgaveStatus,
    opprettetDato: z.iso.datetime({ local: true }),
    løstDato: z.optional(z.iso.datetime({ local: true })),
    åpnetDato: z.optional(z.iso.datetime({ local: true })),
    lukketDato: z.optional(z.iso.datetime({ local: true })),
    frist: z.optional(z.iso.datetime({ local: true })),
});

export const zDeltakelseKomposittDto = z.object({
    id: z.optional(z.uuid()),
    deltaker: zDeltakerDto,
    fraOgMed: z.iso.date(),
    tilOgMed: z.optional(z.iso.date()),
    søktTidspunkt: z.optional(z.iso.datetime({ local: true })),
    oppgaver: z.array(zOppgaveDto),
});

export const zKontonummerDto = z.object({
    harKontonummer: z.boolean(),
    kontonummer: z.optional(z.string()),
});

export const zMarkerDeltakelseSomSøktData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid(),
    }),
    query: z.optional(z.never()),
});

/**
 * OK
 */
export const zMarkerDeltakelseSomSøktResponse = zDeltakelseKomposittDto;

export const zHentKontonummerData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});

/**
 * OK
 */
export const zHentKontonummerResponse = zKontonummerDto;

export const zHentDeltakersOppgaveData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        oppgaveReferanse: z.uuid(),
    }),
    query: z.optional(z.never()),
});

/**
 * OK
 */
export const zHentDeltakersOppgaveResponse = zOppgaveDto;

export const zMarkerOppgaveSomLøstData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        oppgaveReferanse: z.uuid(),
    }),
    query: z.optional(z.never()),
});

/**
 * OK
 */
export const zMarkerOppgaveSomLøstResponse = zOppgaveDto;

export const zMarkerOppgaveSomLukketData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        oppgaveReferanse: z.uuid(),
    }),
    query: z.optional(z.never()),
});

/**
 * OK
 */
export const zMarkerOppgaveSomLukketResponse = zOppgaveDto;

export const zMarkerOppgaveSomÅpnetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        oppgaveReferanse: z.uuid(),
    }),
    query: z.optional(z.never()),
});

/**
 * OK
 */
export const zMarkerOppgaveSomÅpnetResponse = zOppgaveDto;

export const zHentAlleMineDeltakelserData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});

/**
 * OK
 */
export const zHentAlleMineDeltakelserResponse = z.array(zDeltakelseKomposittDto);
