// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zDeltakerDto = z.object({
    deltakerIdent: z.string(),
    id: z.uuid().nullish(),
});

export const zDeltakelseDto = z.object({
    deltaker: zDeltakerDto,
    erSlettet: z.boolean(),
    fraOgMed: z.iso.date(),
    harOpphørsvedtak: z.boolean(),
    id: z.uuid().nullish(),
    søktTidspunkt: z.iso.datetime({ local: true }).nullish(),
    tilOgMed: z.iso.date().nullish(),
});

export const zDeltakelseKomposittDto = z.object({
    deltaker: zDeltakerDto,
    erSlettet: z.boolean(),
    fraOgMed: z.iso.date(),
    harOpphørsvedtak: z.boolean(),
    id: z.uuid().nullish(),
    oppgaver: z.array(z.unknown()),
    søktTidspunkt: z.iso.datetime({ local: true }).nullish(),
    tilOgMed: z.iso.date().nullish(),
});

export const zKontonummerDto = z.object({
    harKontonummer: z.boolean(),
    kontonummer: z.string().nullish(),
});

export const zProblemDetail = z.object({
    detail: z.string().optional(),
    instance: z.url().optional(),
    properties: z.record(z.string(), z.unknown()).optional(),
    status: z
        .int()
        .min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' })
        .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
        .optional(),
    title: z.string().optional(),
    type: z.url().optional(),
});

/**
 * OK
 */
export const zHentAlleMineDeltakelserResponse = z.array(zDeltakelseKomposittDto);

/**
 * OK
 */
export const zHentAlleMineDeltakelserV2Response = z.array(zDeltakelseDto);

export const zMarkerDeltakelseSomSøktPath = z.object({
    id: z.uuid(),
});

/**
 * OK
 */
export const zMarkerDeltakelseSomSøktResponse = zDeltakelseKomposittDto;

export const zMarkerDeltakelseSomSøktV2Path = z.object({
    id: z.uuid(),
});

/**
 * OK
 */
export const zMarkerDeltakelseSomSøktV2Response = zDeltakelseDto;

/**
 * OK
 */
export const zHentKontonummerResponse = zKontonummerDto;
