apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
    name: {{app}}
    namespace: {{namespace}}
    labels:
        team: {{team}}
    annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "100M"
spec:
    image: {{ image }}
    port: 8080
    liveness:
        path: {{livenessPath}}
        initialDelay: 20
        timeout: 1
        periodSeconds: 5
        failureThreshold: 10
    readiness:
        path: {{readinessPath}}
        initialDelay: 20
        timeout: 1
    resources:
        limits:
            memory: {{#if resources.limits.memory}}{{resources.limits.memory}}{{else}}512Mi{{/if}}
        requests:
            cpu: {{#if resources.requests.cpu}}{{resources.requests.cpu}}{{else}}40m{{/if}}
            memory: {{#if resources.requests.memory}}{{resources.requests.memory}}{{else}}128Mi{{/if}}
    accessPolicy:
        outbound:
            rules:
            {{#each accessPolicyOutApps as |rule|}}
             - application: {{rule.application}}
               namespace: {{rule.namespace}}
            {{/each}}
             - application: nav-dekoratoren
               namespace: personbruker
            external:
            {{#each externalHosts as |host|}}
            - host: {{host}}
            {{/each}}
    ingresses:
      {{#each ingresses as |url|}}
       - {{url}}
          {{/each}}
    replicas:
        min: {{ minReplicas }}
        max: {{ maxReplicas }}
        cpuThresholdPercentage: 90
    {{#if faro}}
    frontend:
        generatedConfig:
            mountPath: /apps/{{app}}/dist/assets/nais.js
    {{/if}}
    prometheus:
        enabled: true
        path: /metrics
    vault:
        enabled: false
    observability:
      logging:
        destinations:
          - id: loki
          - id: elastic
      autoInstrumentation:
        enabled: {{observabilityEnabled}}
        runtime: nodejs
    env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
    {{/each}}
     - name: IMAGE
       value: {{image}}
     - name: GITHUB_REF_NAME
       value: {{GITHUB_REF_NAME}}
     - name: NEXT_PUBLIC_GITHUB_REF_NAME
       value: {{GITHUB_REF_NAME}}
       
    tokenx:
         enabled: true
    idporten:
        enabled: true
        sidecar:
            {{#unless skipAutologin}}
            autoLogin: true
            {{/unless}}
            autoLoginIgnorePaths:
                - {{env.PUBLIC_PATH}}/assets/*
            enabled: true
