export type {
    DeleteMellomlagringData,
    DeleteMellomlagringResponses,
    DeleteMellomlagringErrors,
    GetMellomlagringData,
    GetMellomlagringResponses,
    GetMellomlagringErrors,
    GetMellomlagringResponse,
    CreateMellomlagringData,
    CreateMellomlagringResponses,
    CreateMellomlagringErrors,
    UpdateMellomlagringData,
    UpdateMellomlagringResponses,
    UpdateMellomlagringErrors,
} from '@navikt/k9-brukerdialog-prosessering-api';
