apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
    name: {{app}}
    namespace: {{namespace}}
    labels:
        team: {{team}}
spec:
    port: 3000
    image: {{ image }}
    liveness:
        path: {{livenessPath}}
        initialDelay: 20
        timeout: 60
    readiness:
        path: {{readinessPath}}
        initialDelay: 20
        timeout: 60
    replicas:
        min: 2
        max: 2
    resources:
        requests:
            cpu: 200m
            memory: 256Mi
        limits:
            memory: 256Mi
    ingresses:
    {{#each ingresses as |url|}}
        - {{url}}
    {{/each}}
    filesFrom:
      - emptyDir:
          medium: Memory
        mountPath: /app/.next/cache
    accessPolicy:
        outbound:
            rules:
              - application: nav-dekoratoren
                namespace: personbruker
            external:
            {{#each externalHosts as |host|}}
            - host: {{host}}
            {{/each}}
    env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
    {{/each}}