// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zProblemDetail = z.object({
    type: z.string().url().optional(),
    title: z.string().optional(),
    status: z.number().int().optional(),
    detail: z.string().optional(),
    instance: z.string().url().optional(),
    properties: z.object({}).optional(),
});

export const zOmsorgsdagerKronsinskSuktBarnRequestDto = z.object({
    pleietrengendeAktørId: z.string(),
});

export const zHentSisteGyldigeVedtakForAktorIdResponse = z.object({
    harInnvilgedeBehandlinger: z.boolean(),
    saksnummer: z.string().optional(),
    vedtaksdato: z.string().date().optional(),
});

export const zPeriode = z.object({
    fom: z.string().date(),
    tom: z.string().date(),
});

export const zOpplæringsinstitusjon = z.object({
    uuid: z.string().uuid(),
    navn: z.string(),
    perioder: z.array(zPeriode),
});

export const zHentSisteGyldigeVedtakForAktorIdData = z.object({
    body: zOmsorgsdagerKronsinskSuktBarnRequestDto,
    path: z.never().optional(),
    query: z.never().optional(),
});

/**
 * OK
 */
export const zHentSisteGyldigeVedtakForAktorIdResponse2 = zHentSisteGyldigeVedtakForAktorIdResponse;

export const zHentOpplæringsinstitusjonerData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional(),
});

/**
 * OK
 */
export const zHentOpplæringsinstitusjonerResponse = z.array(zOpplæringsinstitusjon);
