module.exports = {
    PUBLIC_PATH: `${process.env.PUBLIC_PATH}`,
    NAIS_CLIENT_ID: `${process.env.NAIS_CLIENT_ID}`,
    DEKORATOR_URL: `${process.env.DEKORATOR_URL}`,

    /** API adresser */
    BRUKERDIALOG_PROSESSERING_FRONTEND_PATH: `${process.env.BRUKERDIALOG_PROSESSERING_FRONTEND_PATH}`,
    BRUKERDIALOG_PROSESSERING_SERVER_URL: `${process.env.BRUKERDIALOG_PROSESSERING_SERVER_URL}`,
    BRUKERDIALOG_PROSESSERING_TOKENX_AUDIENCE: `${process.env.BRUKERDIALOG_PROSESSERING_TOKENX_AUDIENCE}`,
    K9_SAK_INNSYN_FRONTEND_PATH: `${process.env.K9_SAK_INNSYN_FRONTEND_PATH}`,
    K9_SAK_INNSYN_SERVER_URL: `${process.env.K9_SAK_INNSYN_SERVER_URL}`,
    K9_SAK_INNSYN_TOKENX_AUDIENCE: `${process.env.K9_SAK_INNSYN_TOKENX_AUDIENCE}`,
    SIF_INNSYN_FRONTEND_PATH: `${process.env.SIF_INNSYN_FRONTEND_PATH}`,
    SIF_INNSYN_SERVER_URL: `${process.env.SIF_INNSYN_SERVER_URL}`,
    SIF_INNSYN_TOKENX_AUDIENCE: `${process.env.SIF_INNSYN_TOKENX_AUDIENCE}`,
};
