// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type {
    EndreStartdatoData,
    EndreStartdatoResponses,
    EndreStartdatoErrors,
    EndreSluttdatoData,
    EndreSluttdatoResponses,
    EndreSluttdatoErrors,
    MeldUtDeltakerData,
    MeldUtDeltakerResponses,
    MeldUtDeltakerErrors,
    MarkerDeltakelseSomSøktData,
    MarkerDeltakelseSomSøktResponses,
    MarkerDeltakelseSomSøktErrors,
    MeldInnDeltakerData,
    MeldInnDeltakerResponses,
    MeldInnDeltakerErrors,
    HentAlleDeltakelserGittDeltakerAktørData,
    HentAlleDeltakelserGittDeltakerAktørResponses,
    HentAlleDeltakelserGittDeltakerAktørErrors,
    HentDeltakerInfoGittDeltakerData,
    HentDeltakerInfoGittDeltakerResponses,
    HentDeltakerInfoGittDeltakerErrors,
    UtløperOppgaveData,
    UtløperOppgaveResponses,
    UtløperOppgaveErrors,
    UtløperOppgaveForTypeOgPeriodeData,
    UtløperOppgaveForTypeOgPeriodeResponses,
    UtløperOppgaveForTypeOgPeriodeErrors,
    OpprettOppgaveForKontrollAvRegisterinntektData,
    OpprettOppgaveForKontrollAvRegisterinntektResponses,
    OpprettOppgaveForKontrollAvRegisterinntektErrors,
    OpprettOppgaveForInntektsrapporteringData,
    OpprettOppgaveForInntektsrapporteringResponses,
    OpprettOppgaveForInntektsrapporteringErrors,
    OpprettOppgaveForEndretStartdatoData,
    OpprettOppgaveForEndretStartdatoResponses,
    OpprettOppgaveForEndretStartdatoErrors,
    OpprettOppgaveForEndretSluttdatoData,
    OpprettOppgaveForEndretSluttdatoResponses,
    OpprettOppgaveForEndretSluttdatoErrors,
    AvbrytOppgaveData,
    AvbrytOppgaveResponses,
    AvbrytOppgaveErrors,
    HentAlleDeltakelserGittDeltakerIdData,
    HentAlleDeltakelserGittDeltakerIdResponses,
    HentAlleDeltakelserGittDeltakerIdErrors,
    DeltakelseHistorikkData,
    DeltakelseHistorikkResponses,
    DeltakelseHistorikkErrors,
    HentDeltakerInfoGittDeltakerIdData,
    HentDeltakerInfoGittDeltakerIdResponses,
    HentDeltakerInfoGittDeltakerIdErrors,
    HentKontonummerData,
    HentKontonummerResponses,
    HentKontonummerErrors,
    HentDeltakersOppgaveData,
    HentDeltakersOppgaveResponses,
    HentDeltakersOppgaveErrors,
    MarkerOppgaveSomLøstData,
    MarkerOppgaveSomLøstResponses,
    MarkerOppgaveSomLøstErrors,
    MarkerOppgaveSomLukketData,
    MarkerOppgaveSomLukketResponses,
    MarkerOppgaveSomLukketErrors,
    MarkerOppgaveSomÅpnetData,
    MarkerOppgaveSomÅpnetResponses,
    MarkerOppgaveSomÅpnetErrors,
    HentAlleMineDeltakelserData,
    HentAlleMineDeltakelserResponses,
    HentAlleMineDeltakelserErrors,
    FjernFraProgramData,
    FjernFraProgramResponses,
    FjernFraProgramErrors,
} from './types.gen';
import {
    zEndreStartdatoData,
    zEndreStartdatoResponse,
    zEndreSluttdatoData,
    zEndreSluttdatoResponse,
    zMeldUtDeltakerData,
    zMeldUtDeltakerResponse,
    zMarkerDeltakelseSomSøktData,
    zMarkerDeltakelseSomSøktResponse,
    zMeldInnDeltakerData,
    zMeldInnDeltakerResponse,
    zHentAlleDeltakelserGittDeltakerAktørData,
    zHentAlleDeltakelserGittDeltakerAktørResponse,
    zHentDeltakerInfoGittDeltakerData,
    zHentDeltakerInfoGittDeltakerResponse,
    zUtløperOppgaveData,
    zUtløperOppgaveForTypeOgPeriodeData,
    zOpprettOppgaveForKontrollAvRegisterinntektData,
    zOpprettOppgaveForKontrollAvRegisterinntektResponse,
    zOpprettOppgaveForInntektsrapporteringData,
    zOpprettOppgaveForInntektsrapporteringResponse,
    zOpprettOppgaveForEndretStartdatoData,
    zOpprettOppgaveForEndretStartdatoResponse,
    zOpprettOppgaveForEndretSluttdatoData,
    zOpprettOppgaveForEndretSluttdatoResponse,
    zAvbrytOppgaveData,
    zHentAlleDeltakelserGittDeltakerIdData,
    zHentAlleDeltakelserGittDeltakerIdResponse,
    zDeltakelseHistorikkData,
    zDeltakelseHistorikkResponse,
    zHentDeltakerInfoGittDeltakerIdData,
    zHentDeltakerInfoGittDeltakerIdResponse,
    zHentKontonummerData,
    zHentKontonummerResponse,
    zHentDeltakersOppgaveData,
    zHentDeltakersOppgaveResponse,
    zMarkerOppgaveSomLøstData,
    zMarkerOppgaveSomLøstResponse,
    zMarkerOppgaveSomLukketData,
    zMarkerOppgaveSomLukketResponse,
    zMarkerOppgaveSomÅpnetData,
    zMarkerOppgaveSomÅpnetResponse,
    zHentAlleMineDeltakelserData,
    zHentAlleMineDeltakelserResponse,
    zFjernFraProgramData,
    zFjernFraProgramResponse,
} from './zod.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<
    TData,
    ThrowOnError
> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Veileder {
    /**
     * Endrer startdato på en deltakelse i ungdomsprogrammet
     */
    public static endreStartdato<ThrowOnError extends boolean = true>(
        options: Options<EndreStartdatoData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).put<EndreStartdatoResponses, EndreStartdatoErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zEndreStartdatoData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zEndreStartdatoResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/veileder/register/deltakelse/{deltakelseId}/endre/startdato',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }

    /**
     * Endrer startdato på en deltakelse i ungdomsprogrammet
     */
    public static endreSluttdato<ThrowOnError extends boolean = true>(
        options: Options<EndreSluttdatoData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).put<EndreSluttdatoResponses, EndreSluttdatoErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zEndreSluttdatoData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zEndreSluttdatoResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/veileder/register/deltakelse/{deltakelseId}/endre/sluttdato',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }

    /**
     * Avslutter en deltakelse i ungdomsprogrammet
     */
    public static meldUtDeltaker<ThrowOnError extends boolean = true>(
        options: Options<MeldUtDeltakerData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).put<MeldUtDeltakerResponses, MeldUtDeltakerErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zMeldUtDeltakerData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zMeldUtDeltakerResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/veileder/register/deltakelse/{deltakelseId}/avslutt',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }

    /**
     * Meld inn en deltaker i ungdomsprogrammet.
     */
    public static meldInnDeltaker<ThrowOnError extends boolean = true>(
        options: Options<MeldInnDeltakerData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<MeldInnDeltakerResponses, MeldInnDeltakerErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zMeldInnDeltakerData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zMeldInnDeltakerResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/veileder/register/deltaker/innmelding',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }

    /**
     * Hent alle deltakelser for en deltaker i ungdomsprogrammet
     */
    public static hentAlleDeltakelserGittDeltakerId<ThrowOnError extends boolean = true>(
        options: Options<HentAlleDeltakelserGittDeltakerIdData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).get<
            HentAlleDeltakelserGittDeltakerIdResponses,
            HentAlleDeltakelserGittDeltakerIdErrors,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zHentAlleDeltakelserGittDeltakerIdData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zHentAlleDeltakelserGittDeltakerIdResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/veileder/register/deltaker/{deltakerId}/deltakelser',
            ...options,
        });
    }

    public static deltakelseHistorikk<ThrowOnError extends boolean = true>(
        options: Options<DeltakelseHistorikkData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).get<
            DeltakelseHistorikkResponses,
            DeltakelseHistorikkErrors,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zDeltakelseHistorikkData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zDeltakelseHistorikkResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/veileder/register/deltakelse/{deltakelseId}/historikk',
            ...options,
        });
    }

    /**
     * Fjern en deltaker fra ungdomsprogrammet
     */
    public static fjernFraProgram<ThrowOnError extends boolean = true>(
        options: Options<FjernFraProgramData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).delete<FjernFraProgramResponses, FjernFraProgramErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zFjernFraProgramData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zFjernFraProgramResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/veileder/register/deltaker/{deltakerId}/fjern',
            ...options,
        });
    }
}

export class Deltakelse {
    /**
     * Markerer at deltakelsen er søkt om
     */
    public static markerDeltakelseSomSøkt<ThrowOnError extends boolean = true>(
        options: Options<MarkerDeltakelseSomSøktData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).put<
            MarkerDeltakelseSomSøktResponses,
            MarkerDeltakelseSomSøktErrors,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zMarkerDeltakelseSomSøktData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zMarkerDeltakelseSomSøktResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/deltakelse/register/{id}/marker-har-sokt',
            ...options,
        });
    }

    /**
     * Henter en oppgave for en gitt deltakelse
     */
    public static hentDeltakersOppgave<ThrowOnError extends boolean = true>(
        options: Options<HentDeltakersOppgaveData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).get<
            HentDeltakersOppgaveResponses,
            HentDeltakersOppgaveErrors,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zHentDeltakersOppgaveData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zHentDeltakersOppgaveResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/deltakelse/register/oppgave/{oppgaveReferanse}',
            ...options,
        });
    }

    /**
     * Markerer en oppgave som åpnet
     */
    public static markerOppgaveSomLøst<ThrowOnError extends boolean = true>(
        options: Options<MarkerOppgaveSomLøstData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).get<
            MarkerOppgaveSomLøstResponses,
            MarkerOppgaveSomLøstErrors,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zMarkerOppgaveSomLøstData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zMarkerOppgaveSomLøstResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/deltakelse/register/oppgave/{oppgaveReferanse}/løst',
            ...options,
        });
    }

    /**
     * Markerer en oppgave som lukket
     */
    public static markerOppgaveSomLukket<ThrowOnError extends boolean = true>(
        options: Options<MarkerOppgaveSomLukketData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).get<
            MarkerOppgaveSomLukketResponses,
            MarkerOppgaveSomLukketErrors,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zMarkerOppgaveSomLukketData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zMarkerOppgaveSomLukketResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/deltakelse/register/oppgave/{oppgaveReferanse}/lukk',
            ...options,
        });
    }

    /**
     * Markerer en oppgave som åpnet
     */
    public static markerOppgaveSomÅpnet<ThrowOnError extends boolean = true>(
        options: Options<MarkerOppgaveSomÅpnetData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).get<
            MarkerOppgaveSomÅpnetResponses,
            MarkerOppgaveSomÅpnetErrors,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zMarkerOppgaveSomÅpnetData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zMarkerOppgaveSomÅpnetResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/deltakelse/register/oppgave/{oppgaveReferanse}/apnet',
            ...options,
        });
    }

    /**
     * Henter alle deltakelser for en deltaker i ungdomsprogrammet
     */
    public static hentAlleMineDeltakelser<ThrowOnError extends boolean = true>(
        options?: Options<HentAlleMineDeltakelserData, ThrowOnError>,
    ) {
        return (options?.client ?? _heyApiClient).get<
            HentAlleMineDeltakelserResponses,
            HentAlleMineDeltakelserErrors,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zHentAlleMineDeltakelserData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zHentAlleMineDeltakelserResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/deltakelse/register/hent/alle',
            ...options,
        });
    }
}

export class LesRegisterData {
    /**
     * Hent alle deltakelser for en deltaker i ungdomsprogrammet
     */
    public static hentAlleDeltakelserGittDeltakerAktør<ThrowOnError extends boolean = true>(
        options: Options<HentAlleDeltakelserGittDeltakerAktørData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            HentAlleDeltakelserGittDeltakerAktørResponses,
            HentAlleDeltakelserGittDeltakerAktørErrors,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zHentAlleDeltakelserGittDeltakerAktørData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zHentAlleDeltakelserGittDeltakerAktørResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/register/hent/alle',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }
}

export class Oppslag {
    /**
     * Hent personalia for en deltaker
     */
    public static hentDeltakerInfoGittDeltaker<ThrowOnError extends boolean = true>(
        options: Options<HentDeltakerInfoGittDeltakerData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            HentDeltakerInfoGittDeltakerResponses,
            HentDeltakerInfoGittDeltakerErrors,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zHentDeltakerInfoGittDeltakerData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zHentDeltakerInfoGittDeltakerResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/oppslag/deltaker',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }

    /**
     * Hent personlia for en deltaker gitt en UUID
     */
    public static hentDeltakerInfoGittDeltakerId<ThrowOnError extends boolean = true>(
        options: Options<HentDeltakerInfoGittDeltakerIdData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).get<
            HentDeltakerInfoGittDeltakerIdResponses,
            HentDeltakerInfoGittDeltakerIdErrors,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zHentDeltakerInfoGittDeltakerIdData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zHentDeltakerInfoGittDeltakerIdResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/oppslag/deltaker/{id}',
            ...options,
        });
    }
}

export class OppretterOgEndrerPåOppgaver {
    /**
     * Setter oppgave til utløpt
     */
    public static utløperOppgave<ThrowOnError extends boolean = true>(
        options: Options<UtløperOppgaveData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<UtløperOppgaveResponses, UtløperOppgaveErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zUtløperOppgaveData.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/oppgave/utlopt',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }

    /**
     * Setter oppgave til utløpt for type og periode
     */
    public static utløperOppgaveForTypeOgPeriode<ThrowOnError extends boolean = true>(
        options: Options<UtløperOppgaveForTypeOgPeriodeData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            UtløperOppgaveForTypeOgPeriodeResponses,
            UtløperOppgaveForTypeOgPeriodeErrors,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zUtløperOppgaveForTypeOgPeriodeData.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/oppgave/utlopt/forTypeOgPeriode',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }

    /**
     * Oppretter oppgave for kontroll av registerinntekt
     */
    public static opprettOppgaveForKontrollAvRegisterinntekt<ThrowOnError extends boolean = true>(
        options: Options<OpprettOppgaveForKontrollAvRegisterinntektData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            OpprettOppgaveForKontrollAvRegisterinntektResponses,
            OpprettOppgaveForKontrollAvRegisterinntektErrors,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zOpprettOppgaveForKontrollAvRegisterinntektData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zOpprettOppgaveForKontrollAvRegisterinntektResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/oppgave/opprett/kontroll/registerinntekt',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }

    /**
     * Oppretter oppgave for inntektsrapportering
     */
    public static opprettOppgaveForInntektsrapportering<ThrowOnError extends boolean = true>(
        options: Options<OpprettOppgaveForInntektsrapporteringData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            OpprettOppgaveForInntektsrapporteringResponses,
            OpprettOppgaveForInntektsrapporteringErrors,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zOpprettOppgaveForInntektsrapporteringData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zOpprettOppgaveForInntektsrapporteringResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/oppgave/opprett/inntektsrapportering',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }

    /**
     * Oppretter oppgave for endret startdato
     */
    public static opprettOppgaveForEndretStartdato<ThrowOnError extends boolean = true>(
        options: Options<OpprettOppgaveForEndretStartdatoData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            OpprettOppgaveForEndretStartdatoResponses,
            OpprettOppgaveForEndretStartdatoErrors,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zOpprettOppgaveForEndretStartdatoData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zOpprettOppgaveForEndretStartdatoResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/oppgave/opprett/endret-startdato',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }

    /**
     * Oppretter oppgave for endret sluttdato
     */
    public static opprettOppgaveForEndretSluttdato<ThrowOnError extends boolean = true>(
        options: Options<OpprettOppgaveForEndretSluttdatoData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<
            OpprettOppgaveForEndretSluttdatoResponses,
            OpprettOppgaveForEndretSluttdatoErrors,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zOpprettOppgaveForEndretSluttdatoData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zOpprettOppgaveForEndretSluttdatoResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/oppgave/opprett/endret-sluttdato',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }

    /**
     * Avbryter oppgave
     */
    public static avbrytOppgave<ThrowOnError extends boolean = true>(
        options: Options<AvbrytOppgaveData, ThrowOnError>,
    ) {
        return (options.client ?? _heyApiClient).post<AvbrytOppgaveResponses, AvbrytOppgaveErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zAvbrytOppgaveData.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/oppgave/avbryt',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }
}

export class Deltaker {
    /**
     * Henter kontonummer for en deltaker i ungdomsprogrammet
     */
    public static hentKontonummer<ThrowOnError extends boolean = true>(
        options?: Options<HentKontonummerData, ThrowOnError>,
    ) {
        return (options?.client ?? _heyApiClient).get<HentKontonummerResponses, HentKontonummerErrors, ThrowOnError>({
            requestValidator: async (data) => {
                return await zHentKontonummerData.parseAsync(data);
            },
            responseType: 'json',
            responseValidator: async (data) => {
                return await zHentKontonummerResponse.parseAsync(data);
            },
            security: [
                {
                    scheme: 'bearer',
                    type: 'http',
                },
                {
                    scheme: 'bearer',
                    type: 'http',
                },
            ],
            url: '/deltaker/hent-kontonummer',
            ...options,
        });
    }
}
