// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zProblemDetail = z.object({
    type: z.string().url().optional(),
    title: z.string().optional(),
    status: z.number().int().optional(),
    detail: z.string().optional(),
    instance: z.string().url().optional(),
    properties: z.object({}).optional(),
});

export const zEndrePeriodeDatoDto = z.object({
    dato: z.string().date(),
});

export const zArbeidOgFrilansRegisterInntektDto = z.object({
    inntekt: z.number().int(),
    arbeidsgiver: z.string(),
});

export const zDeltakerDto = z.object({
    id: z.string().uuid().optional(),
    deltakerIdent: z.string(),
});

export const zOppgavetype = z.enum(['BEKREFT_ENDRET_PROGRAMPERIODE', 'BEKREFT_AVVIK_REGISTERINNTEKT']);

export const zOppgavetypeDataDto = z.object({});

export const zProgramperiodeDto = z.object({
    fomDato: z.string().date(),
    tomDato: z.string().date().optional(),
});

export const zEndretProgramperiodeDataDto = zOppgavetypeDataDto.merge(
    z.object({
        programperiode: zProgramperiodeDto,
        forrigeProgramperiode: zProgramperiodeDto.optional(),
    }),
);

export const zYtelseRegisterInntektDto = z.object({
    inntekt: z.number().int(),
    ytelsetype: z.string(),
});

export const zRegisterinntektDto = z.object({
    arbeidOgFrilansInntekter: z.array(zArbeidOgFrilansRegisterInntektDto),
    ytelseInntekter: z.array(zYtelseRegisterInntektDto),
    totalInntektArbeidOgFrilans: z.number().int(),
    totalInntektYtelse: z.number().int(),
    totalInntekt: z.number().int(),
});

export const zKontrollerRegisterinntektOppgavetypeDataDto = zOppgavetypeDataDto.merge(
    z.object({
        fraOgMed: z.string().date(),
        tilOgMed: z.string().date(),
        registerinntekt: zRegisterinntektDto,
    }),
);

export const zOppgaveStatus = z.enum(['LØST', 'ULØST', 'AVBRUTT', 'UTLØPT']);

export const zOppgaveDto = z.object({
    oppgaveReferanse: z.string().uuid(),
    oppgavetype: zOppgavetype,
    oppgavetypeData: z.union([zEndretProgramperiodeDataDto, zKontrollerRegisterinntektOppgavetypeDataDto]),
    status: zOppgaveStatus,
    opprettetDato: z.string().datetime(),
    løstDato: z.string().datetime().optional(),
});

export const zDeltakelseOpplysningDto = z.object({
    id: z.string().uuid().optional(),
    deltaker: zDeltakerDto,
    fraOgMed: z.string().date(),
    tilOgMed: z.string().date().optional(),
    harSøkt: z.boolean(),
    oppgaver: z.array(zOppgaveDto),
});

export const zDeltakelseUtmeldingDto = z.object({
    utmeldingsdato: z.string().date(),
});

export const zDeltakelseInnmeldingDto = z.object({
    deltakerIdent: z.string(),
    startdato: z.string().date(),
});

export const zAktørIdDto = z.object({
    aktørId: z.string(),
});

export const zDeltakerOpplysningerDto = z.object({
    opplysninger: z.array(zDeltakelseOpplysningDto),
});

export const zNavn = z.object({
    fornavn: z.string(),
    mellomnavn: z.string().optional(),
    etternavn: z.string(),
});

export const zDeltakerPersonlia = z.object({
    id: z.string().uuid().optional(),
    deltakerIdent: z.string(),
    navn: zNavn,
    fødselsdato: z.string().date(),
    førsteMuligeInnmeldingsdato: z.string().date(),
    sisteMuligeInnmeldingsdato: z.string().date(),
});

export const zRegisterInntektArbeidOgFrilansDto = z.object({
    beløp: z.number().int(),
    arbeidsgiverIdent: z.string(),
});

export const zRegisterInntektYtelseDto = z.object({
    beløp: z.number().int(),
    ytelseType: z.string(),
});

export const zRegisterInntektDto = z.object({
    registerinntekterForArbeidOgFrilans: z.array(zRegisterInntektArbeidOgFrilansDto).optional(),
    registerinntekterForYtelse: z.array(zRegisterInntektYtelseDto).optional(),
});

export const zRegisterInntektOppgaveDto = z.object({
    deltakerIdent: z.string(),
    referanse: z.string().uuid(),
    frist: z.string().datetime(),
    fomDato: z.string().date(),
    tomDato: z.string().date(),
    registerInntekter: zRegisterInntektDto,
});

export const zEndretProgamperiodeOppgaveDto = z.object({
    deltakerIdent: z.string(),
    oppgaveReferanse: z.string().uuid(),
    frist: z.string().datetime(),
    programperiode: zProgramperiodeDto,
    forrigeProgramperiode: zProgramperiodeDto.optional(),
});

export const zKontonummerDto = z.object({
    kontonummer: z.string(),
});

export const zRapportPeriodeinfoDto = z.object({
    fraOgMed: z.string().date(),
    tilOgMed: z.string().date(),
    harRapportert: z.boolean(),
    arbeidstakerOgFrilansInntekt: z.number().optional(),
    inntektFraYtelse: z.number().optional(),
    summertInntekt: z.number().optional(),
});

export const zDeltakelsePeriodInfo = z.object({
    id: z.string().uuid(),
    fraOgMed: z.string().date(),
    tilOgMed: z.string().date().optional(),
    harSøkt: z.boolean(),
    oppgaver: z.array(zOppgaveDto),
    rapporteringsPerioder: z.array(zRapportPeriodeinfoDto),
});

export const zEndreStartdatoResponse = zDeltakelseOpplysningDto;

export const zEndreSluttdatoResponse = zDeltakelseOpplysningDto;

export const zMeldUtDeltakerResponse = zDeltakelseOpplysningDto;

export const zMarkerDeltakelseSomSøktResponse = zDeltakelseOpplysningDto;

export const zMeldInnDeltakerResponse = zDeltakelseOpplysningDto;

export const zHentAlleDeltakelserGittDeltakerAktørResponse = zDeltakerOpplysningerDto;

export const zHentDeltakerInfoGittDeltakerResponse = zDeltakerPersonlia;

export const zKontrollAvRegisterinntektResponse = zOppgaveDto;

export const zOpprettOppgaveForKontrollAvRegisterinntektResponse = zOppgaveDto;

export const zOpprettOppgaveForEndretProgramperiodeResponse = zOppgaveDto;

export const zHentAlleDeltakelserGittDeltakerIdResponse = z.array(zDeltakelseOpplysningDto);

export const zHentDeltakerInfoGittDeltakerIdResponse = zDeltakerPersonlia;

export const zHentKontonummerResponse = zKontonummerDto;

export const zHentDeltakersOppgaveResponse = zOppgaveDto;

export const zHentAlleMineDeltakelserResponse = z.array(zDeltakelsePeriodInfo);

export const zFjernFraProgramResponse = z.void();
