export enum SIF_ENV {
    'ENV' = 'ENV',
    'APP_VERSION' = 'APP_VERSION',
    'PUBLIC_PATH' = 'PUBLIC_PATH',
    'GITHUB_REF_NAME' = 'GITHUB_REF_NAME',
    'SIF_PUBLIC_DEKORATOR_URL' = 'SIF_PUBLIC_DEKORATOR_URL',
    'SIF_PUBLIC_LOGIN_URL' = 'SIF_PUBLIC_LOGIN_URL',
    'SIF_PUBLIC_MINSIDE_URL' = 'SIF_PUBLIC_MINSIDE_URL',
    'SIF_PUBLIC_INNSYN_URL' = 'SIF_PUBLIC_INNSYN_URL',
    'SIF_PUBLIC_APPSTATUS_PROJECT_ID' = 'SIF_PUBLIC_APPSTATUS_PROJECT_ID',
    'SIF_PUBLIC_APPSTATUS_DATASET' = 'SIF_PUBLIC_APPSTATUS_DATASET',
    'SIF_PUBLIC_USE_AMPLITUDE' = 'SIF_PUBLIC_USE_AMPLITUDE',
}

export enum API_BROWSER_ENV {
    'K9_BRUKERDIALOG_PROSESSERING_FRONTEND_PATH' = 'K9_BRUKERDIALOG_PROSESSERING_FRONTEND_PATH',
    'K9_BRUKERDIALOG_PROSESSERING_API_URL' = 'K9_BRUKERDIALOG_PROSESSERING_API_URL',
    'K9_SAK_INNSYN_FRONTEND_PATH' = 'K9_SAK_INNSYN_FRONTEND_PATH',
    'K9_SAK_INNSYN_API_URL' = 'K9_SAK_INNSYN_API_URL',
    'SIF_INNSYN_FRONTEND_PATH' = 'SIF_INNSYN_FRONTEND_PATH',
    'SIF_INNSYN_API_URL' = 'SIF_INNSYN_API_URL',
    'UNG_DELTAKELSE_OPPLYSER_FRONTEND_PATH' = 'UNG_DELTAKELSE_OPPLYSER_FRONTEND_PATH',
    'UNG_DELTAKELSE_OPPLYSER_API_URL' = 'UNG_DELTAKELSE_OPPLYSER_API_URL',
}

export enum API_SERVER_ENV {
    'K9_BRUKERDIALOG_PROSESSERING_API_SCOPE' = 'K9_BRUKERDIALOG_PROSESSERING_API_SCOPE',
    'K9_SAK_INNSYN_API_SCOPE' = 'K9_SAK_INNSYN_API_SCOPE',
    'SIF_INNSYN_API_SCOPE' = 'SIF_INNSYN_API_SCOPE',
    'UNG_DELTAKELSE_OPPLYSER_API_SCOPE' = 'UNG_DELTAKELSE_OPPLYSER_API_SCOPE',
}

export type SIF_ENV_KEY = SIF_ENV | API_BROWSER_ENV;
