export enum ApiEndpoint {
    SEND_DOKUMENTER = 'ettersending/innsending',
    SØKER = 'oppslag/soker',
    BARN = 'oppslag/barn',
    VEDLEGG = 'vedlegg',
    MELLOMLAGRING_PLEIEPENGER_SYKT_BARN = 'mellomlagring/ETTERSENDING_PLEIEPENGER_SYKT_BARN',
    MELLOMLAGRING_PLEIEPENGER_LIVETS_SLUTTFASE = 'mellomlagring/ETTERSENDING_PLEIEPENGER_LIVETS_SLUTTFASE',
    MELLOMLAGRING_OMP = 'mellomlagring/ETTERSENDING_OMP',
    MELLOMLAGRING_OPPLARINGSPENGER = 'mellomlagring/ETTERSENDING_OPPLARINGSPENGER',
}
