// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
    HentAlleOppgaverData,
    HentAlleOppgaverResponses,
    HentOppgaveData,
    HentOppgaveResponses,
    LøsOppgaveData,
    LøsOppgaveResponses,
} from './types.gen';
import {
    zHentAlleOppgaverData,
    zHentAlleOppgaverResponse,
    zHentOppgaveData,
    zHentOppgaveResponse,
    zLøsOppgaveData,
    zLøsOppgaveResponse,
} from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<
    TData,
    ThrowOnError
> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class BrukerdialogOppgave {
    /**
     * Henter alle oppgaver for en bruker
     */
    public static hentAlleOppgaver<ThrowOnError extends boolean = true>(
        options?: Options<HentAlleOppgaverData, ThrowOnError>,
    ) {
        return (options?.client ?? client).get<HentAlleOppgaverResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zHentAlleOppgaverData.parseAsync(data),
            responseValidator: async (data) => await zHentAlleOppgaverResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/ung/brukerdialog/ekstern/api/oppgave/hent/alle',
            ...options,
        });
    }

    /**
     * Henter en spesifikk oppgave basert på oppgaveReferanse
     */
    public static hentOppgave<ThrowOnError extends boolean = true>(options: Options<HentOppgaveData, ThrowOnError>) {
        return (options.client ?? client).get<HentOppgaveResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zHentOppgaveData.parseAsync(data),
            responseValidator: async (data) => await zHentOppgaveResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/ung/brukerdialog/ekstern/api/oppgave/{oppgavereferanse}',
            ...options,
        });
    }

    /**
     * Løser en spesifikk oppgave basert på oppgaveReferanse
     */
    public static løsOppgave<ThrowOnError extends boolean = true>(options: Options<LøsOppgaveData, ThrowOnError>) {
        return (options.client ?? client).post<LøsOppgaveResponses, unknown, ThrowOnError>({
            requestValidator: async (data) => await zLøsOppgaveData.parseAsync(data),
            responseValidator: async (data) => await zLøsOppgaveResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/ung/brukerdialog/ekstern/api/oppgave/{oppgavereferanse}/løs',
            ...options,
            headers: {
                'Content-Type': '*/*',
                ...options.headers,
            },
        });
    }
}
