// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}/ung/brukerdialog` | (string & {});
};

export type BekreftelseDto = (
    | ({
          type: 'VARSEL_SVAR';
      } & SvarPåVarselDto)
    | ({
          type: 'RAPPORTERT_INNTEKT';
      } & InntektsrapporteringRapportertInntektDto)
) & {
    type: string;
};

export type BrukerdialogOppgaveDto = {
    bekreftelse?: BekreftelseDto;
    frist?: string;
    løstDato?: string;
    oppgaveReferanse: string;
    oppgavetype: OppgaveType;
    oppgavetypeData: OppgavetypeDataDto;
    opprettetDato: string;
    status: OppgaveStatus;
};

export enum OppgaveStatus {
    /**
     * LØST
     */
    LØST = 'LØST',
    /**
     * ULØST
     */
    ULØST = 'ULØST',
    /**
     * AVBRUTT
     */
    AVBRUTT = 'AVBRUTT',
    /**
     * UTLØPT
     */
    UTLØPT = 'UTLØPT',
}

export enum OppgaveType {
    /**
     * BEKREFT_ENDRET_STARTDATO
     */
    BEKREFT_ENDRET_STARTDATO = 'BEKREFT_ENDRET_STARTDATO',
    /**
     * BEKREFT_ENDRET_SLUTTDATO
     */
    BEKREFT_ENDRET_SLUTTDATO = 'BEKREFT_ENDRET_SLUTTDATO',
    /**
     * BEKREFT_ENDRET_PERIODE
     */
    BEKREFT_ENDRET_PERIODE = 'BEKREFT_ENDRET_PERIODE',
    /**
     * BEKREFT_FJERNET_PERIODE
     */
    BEKREFT_FJERNET_PERIODE = 'BEKREFT_FJERNET_PERIODE',
    /**
     * BEKREFT_AVVIK_REGISTERINNTEKT
     */
    BEKREFT_AVVIK_REGISTERINNTEKT = 'BEKREFT_AVVIK_REGISTERINNTEKT',
    /**
     * RAPPORTER_INNTEKT
     */
    RAPPORTER_INNTEKT = 'RAPPORTER_INNTEKT',
    /**
     * SØK_YTELSE
     */
    SØK_YTELSE = 'SØK_YTELSE',
}

export type OppgavetypeDataDto = (
    | ({
          type: 'ENDRET_PERIODE';
      } & EndretperiodeEndretPeriodeDataDto)
    | ({
          type: 'ENDRET_SLUTTDATO';
      } & EndretsluttdatoEndretSluttdatoDataDto)
    | ({
          type: 'ENDRET_STARTDATO';
      } & EndretstartdatoEndretStartdatoDataDto)
    | ({
          type: 'FJERNET_PERIODE';
      } & FjernperiodeFjernetPeriodeDataDto)
    | ({
          type: 'INNTEKTSRAPPORTERING';
      } & InntektsrapporteringInntektsrapporteringOppgavetypeDataDto)
    | ({
          type: 'KONTROLLER_REGISTERINNTEKT';
      } & KontrollerregisterinntektKontrollerRegisterinntektOppgavetypeDataDto)
    | ({
          type: 'SØK_YTELSE';
      } & SøkytelseSøkYtelseOppgavetypeDataDto)
) & {
    type: string;
};

export type SvarPåVarselDto = {
    harUttalelse: boolean;
    uttalelseFraBruker?: string;
};

export type EndretperiodeEndretPeriodeDataDto = {
    endringer: EndretperiodePeriodeEndringType[];
    forrigePeriode?: EndretperiodePeriodeDto;
    nyPeriode?: EndretperiodePeriodeDto;
};

export type EndretperiodePeriodeDto = {
    fomDato?: string;
    tomDato?: string;
};

export enum EndretperiodePeriodeEndringType {
    /**
     * ENDRET_STARTDATO
     */
    ENDRET_STARTDATO = 'ENDRET_STARTDATO',
    /**
     * ENDRET_SLUTTDATO
     */
    ENDRET_SLUTTDATO = 'ENDRET_SLUTTDATO',
    /**
     * FJERNET_PERIODE
     */
    FJERNET_PERIODE = 'FJERNET_PERIODE',
    /**
     * ANDRE_ENDRINGER
     */
    ANDRE_ENDRINGER = 'ANDRE_ENDRINGER',
}

export type EndretsluttdatoEndretSluttdatoDataDto = {
    forrigeSluttdato?: string;
    nySluttdato: string;
};

export type EndretstartdatoEndretStartdatoDataDto = {
    forrigeStartdato: string;
    nyStartdato: string;
};

export type FjernperiodeFjernetPeriodeDataDto = {
    forrigeSluttdato?: string;
    forrigeStartdato: string;
};

export type InntektsrapporteringInntektsrapporteringOppgavetypeDataDto = {
    fraOgMed: string;
    gjelderDelerAvMåned: boolean;
    tilOgMed: string;
};

export type InntektsrapporteringRapportertInntektDto = {
    arbeidstakerOgFrilansInntekt: number;
    fraOgMed: string;
    tilOgMed: string;
};

export type KontrollerregisterinntektArbeidOgFrilansRegisterInntektDto = {
    arbeidsgiver?: string;
    arbeidsgiverIdentifikator: string;
    arbeidsgiverNavn?: string;
    inntekt: number;
};

export type KontrollerregisterinntektKontrollerRegisterinntektOppgavetypeDataDto = {
    fraOgMed: string;
    gjelderDelerAvMåned: boolean;
    registerinntekt: KontrollerregisterinntektRegisterinntektDto;
    tilOgMed: string;
};

export type KontrollerregisterinntektRegisterinntektDto = {
    arbeidOgFrilansInntekter?: KontrollerregisterinntektArbeidOgFrilansRegisterInntektDto[];
    totalInntekt: number;
    totalInntektArbeidOgFrilans: number;
    totalInntektYtelse: number;
    ytelseInntekter?: KontrollerregisterinntektYtelseRegisterInntektDto[];
};

export type KontrollerregisterinntektYtelseRegisterInntektDto = {
    inntekt: number;
    ytelsetype: KontrollerregisterinntektYtelseType;
};

export enum KontrollerregisterinntektYtelseType {
    /**
     * DAGPENGER
     */
    DAGPENGER = 'DAGPENGER',
    /**
     * SYKEPENGER
     */
    SYKEPENGER = 'SYKEPENGER',
    /**
     * FORELDREPENGER
     */
    FORELDREPENGER = 'FORELDREPENGER',
    /**
     * PLEIEPENGER
     */
    PLEIEPENGER = 'PLEIEPENGER',
    /**
     * OMSORGSPENGER
     */
    OMSORGSPENGER = 'OMSORGSPENGER',
    /**
     * OPPLÆRINGSPENGER
     */
    OPPLÆRINGSPENGER = 'OPPLÆRINGSPENGER',
    /**
     * AAP
     */
    AAP = 'AAP',
    /**
     * ANNET
     */
    ANNET = 'ANNET',
}

export type SøkytelseSøkYtelseOppgavetypeDataDto = {
    fomDato: string;
};

export type HentAlleOppgaverData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ekstern/api/oppgave/hent/alle';
};

export type HentAlleOppgaverResponses = {
    /**
     * default response
     */
    default: BrukerdialogOppgaveDto[];
};

export type HentAlleOppgaverResponse = HentAlleOppgaverResponses[keyof HentAlleOppgaverResponses];

export type HentOppgaveData = {
    body?: never;
    path: {
        /**
         * Unik referanse til oppgaven
         */
        oppgavereferanse: string;
    };
    query?: never;
    url: '/ekstern/api/oppgave/{oppgavereferanse}';
};

export type HentOppgaveResponses = {
    /**
     * default response
     */
    default: BrukerdialogOppgaveDto;
};

export type HentOppgaveResponse = HentOppgaveResponses[keyof HentOppgaveResponses];
