// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}/ung/brukerdialog` | (string & {});
};

export type ArbeidOgFrilansRegisterInntektDto = {
    arbeidsgiverIdentifikator: string;
    arbeidsgiverNavn?: string;
    inntekt: number;
};

export type BrukerdialogOppgaveDto = {
    frist?: string;
    løstDato?: string;
    oppgaveReferanse: string;
    oppgavetype: OppgaveType;
    oppgavetypeData: OppgavetypeDataDto;
    opprettetDato: string;
    respons?: OppgaveResponsDto;
    status: OppgaveStatus;
};

export type EndretPeriodeDataDto = {
    endringer: PeriodeEndringType[];
    forrigePeriode?: PeriodeDto;
    nyPeriode?: PeriodeDto;
};

export type EndretSluttdatoDataDto = {
    forrigeSluttdato?: string;
    nySluttdato: string;
};

export type EndretStartdatoDataDto = {
    forrigeStartdato: string;
    nyStartdato: string;
};

export type InntektsrapporteringOppgavetypeDataDto = {
    fraOgMed: string;
    gjelderDelerAvMåned: boolean;
    tilOgMed: string;
};

export type KontrollerRegisterinntektOppgavetypeDataDto = {
    fraOgMed: string;
    gjelderDelerAvMåned: boolean;
    registerinntekt: RegisterinntektDto;
    tilOgMed: string;
};

export type LøsOppgaveRequest = {
    oppgaveRespons?: OppgaveResponsDto;
};

export type OppgaveResponsDto = (
    | ({
          type: 'VARSEL_SVAR';
      } & SvarPåVarselDto)
    | ({
          type: 'RAPPORTERT_INNTEKT';
      } & RapportertInntektDto)
) & {
    type: string;
};

export enum OppgaveStatus {
    /**
     * LØST
     */
    LØST = 'LØST',
    /**
     * ULØST
     */
    ULØST = 'ULØST',
    /**
     * AVBRUTT
     */
    AVBRUTT = 'AVBRUTT',
    /**
     * UTLØPT
     */
    UTLØPT = 'UTLØPT',
}

export enum OppgaveType {
    /**
     * BEKREFT_ENDRET_STARTDATO
     */
    BEKREFT_ENDRET_STARTDATO = 'BEKREFT_ENDRET_STARTDATO',
    /**
     * BEKREFT_ENDRET_SLUTTDATO
     */
    BEKREFT_ENDRET_SLUTTDATO = 'BEKREFT_ENDRET_SLUTTDATO',
    /**
     * BEKREFT_ENDRET_PERIODE
     */
    BEKREFT_ENDRET_PERIODE = 'BEKREFT_ENDRET_PERIODE',
    /**
     * BEKREFT_AVVIK_REGISTERINNTEKT
     */
    BEKREFT_AVVIK_REGISTERINNTEKT = 'BEKREFT_AVVIK_REGISTERINNTEKT',
    /**
     * RAPPORTER_INNTEKT
     */
    RAPPORTER_INNTEKT = 'RAPPORTER_INNTEKT',
    /**
     * SØK_YTELSE
     */
    SØK_YTELSE = 'SØK_YTELSE',
}

export type OppgavetypeDataDto = (
    | ({
          type: 'ENDRET_PERIODE';
      } & EndretPeriodeDataDto)
    | ({
          type: 'ENDRET_SLUTTDATO';
      } & EndretSluttdatoDataDto)
    | ({
          type: 'ENDRET_STARTDATO';
      } & EndretStartdatoDataDto)
    | ({
          type: 'INNTEKTSRAPPORTERING';
      } & InntektsrapporteringOppgavetypeDataDto)
    | ({
          type: 'KONTROLLER_REGISTERINNTEKT';
      } & KontrollerRegisterinntektOppgavetypeDataDto)
    | ({
          type: 'SØK_YTELSE';
      } & SøkYtelseOppgavetypeDataDto)
) & {
    type: string;
};

export type PeriodeDto = {
    fomDato?: string;
    tomDato?: string;
};

export enum PeriodeEndringType {
    /**
     * ENDRET_STARTDATO
     */
    ENDRET_STARTDATO = 'ENDRET_STARTDATO',
    /**
     * ENDRET_SLUTTDATO
     */
    ENDRET_SLUTTDATO = 'ENDRET_SLUTTDATO',
    /**
     * FJERNET_PERIODE
     */
    FJERNET_PERIODE = 'FJERNET_PERIODE',
    /**
     * ANDRE_ENDRINGER
     */
    ANDRE_ENDRINGER = 'ANDRE_ENDRINGER',
}

export type RapportertInntektDto = {
    arbeidstakerOgFrilansInntekt: number;
    fraOgMed: string;
    tilOgMed: string;
};

export type RegisterinntektDto = {
    arbeidOgFrilansInntekter?: ArbeidOgFrilansRegisterInntektDto[];
    totalInntekt: number;
    totalInntektArbeidOgFrilans: number;
    totalInntektYtelse: number;
    ytelseInntekter?: YtelseRegisterInntektDto[];
};

export type SvarPåVarselDto = {
    harUttalelse: boolean;
    uttalelseFraBruker?: string;
};

export type SøkYtelseOppgavetypeDataDto = {
    fomDato: string;
};

export type YtelseRegisterInntektDto = {
    inntekt: number;
    ytelsetype: YtelseType;
};

export enum YtelseType {
    /**
     * DAGPENGER
     */
    DAGPENGER = 'DAGPENGER',
    /**
     * SYKEPENGER
     */
    SYKEPENGER = 'SYKEPENGER',
    /**
     * FORELDREPENGER
     */
    FORELDREPENGER = 'FORELDREPENGER',
    /**
     * PLEIEPENGER
     */
    PLEIEPENGER = 'PLEIEPENGER',
    /**
     * OMSORGSPENGER
     */
    OMSORGSPENGER = 'OMSORGSPENGER',
    /**
     * OPPLÆRINGSPENGER
     */
    OPPLÆRINGSPENGER = 'OPPLÆRINGSPENGER',
    /**
     * AAP
     */
    AAP = 'AAP',
    /**
     * ANNET
     */
    ANNET = 'ANNET',
}

export type HentAlleOppgaverData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ekstern/api/oppgave/hent/alle';
};

export type HentAlleOppgaverResponses = {
    /**
     * default response
     */
    default: BrukerdialogOppgaveDto[];
};

export type HentAlleOppgaverResponse = HentAlleOppgaverResponses[keyof HentAlleOppgaverResponses];

export type HentOppgaveData = {
    body?: never;
    path: {
        /**
         * Unik referanse til oppgaven
         */
        oppgavereferanse: string;
    };
    query?: never;
    url: '/ekstern/api/oppgave/{oppgavereferanse}';
};

export type HentOppgaveResponses = {
    /**
     * default response
     */
    default: BrukerdialogOppgaveDto;
};

export type HentOppgaveResponse = HentOppgaveResponses[keyof HentOppgaveResponses];

export type LøsOppgaveData = {
    /**
     * Løsningsdata for oppgaven
     */
    body: LøsOppgaveRequest;
    path: {
        /**
         * Unik referanse til oppgaven
         */
        oppgavereferanse: string;
    };
    query?: never;
    url: '/ekstern/api/oppgave/{oppgavereferanse}/løs';
};

export type LøsOppgaveResponses = {
    /**
     * default response
     */
    default: BrukerdialogOppgaveDto;
};

export type LøsOppgaveResponse = LøsOppgaveResponses[keyof LøsOppgaveResponses];
