// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}/ung/brukerdialog` | (string & {});
};

export type UngBrukerdialogKontraktOppgaverBekreftelseDto = (
    | ({
          type: 'VARSEL_SVAR';
      } & UngBrukerdialogKontraktOppgaverSvarPåVarselDto)
    | ({
          type: 'RAPPORTERT_INNTEKT';
      } & UngBrukerdialogKontraktOppgaverTyperInntektsrapporteringRapportertInntektDto)
) & {
    type: string;
};

export type UngBrukerdialogKontraktOppgaverBrukerdialogOppgaveDto = {
    bekreftelse?: UngBrukerdialogKontraktOppgaverBekreftelseDto;
    frist?: string;
    løstDato?: string;
    oppgaveReferanse: string;
    oppgavetype: UngBrukerdialogKontraktOppgaverOppgaveType;
    oppgavetypeData: UngBrukerdialogKontraktOppgaverOppgavetypeDataDto;
    opprettetDato: string;
    status: UngBrukerdialogKontraktOppgaverOppgaveStatus;
};

export enum UngBrukerdialogKontraktOppgaverOppgaveStatus {
    /**
     * LØST
     */
    LØST = 'LØST',
    /**
     * ULØST
     */
    ULØST = 'ULØST',
    /**
     * AVBRUTT
     */
    AVBRUTT = 'AVBRUTT',
    /**
     * UTLØPT
     */
    UTLØPT = 'UTLØPT',
}

export enum UngBrukerdialogKontraktOppgaverOppgaveType {
    /**
     * BEKREFT_ENDRET_STARTDATO
     */
    BEKREFT_ENDRET_STARTDATO = 'BEKREFT_ENDRET_STARTDATO',
    /**
     * BEKREFT_ENDRET_SLUTTDATO
     */
    BEKREFT_ENDRET_SLUTTDATO = 'BEKREFT_ENDRET_SLUTTDATO',
    /**
     * BEKREFT_ENDRET_PERIODE
     */
    BEKREFT_ENDRET_PERIODE = 'BEKREFT_ENDRET_PERIODE',
    /**
     * BEKREFT_FJERNET_PERIODE
     */
    BEKREFT_FJERNET_PERIODE = 'BEKREFT_FJERNET_PERIODE',
    /**
     * BEKREFT_AVVIK_REGISTERINNTEKT
     */
    BEKREFT_AVVIK_REGISTERINNTEKT = 'BEKREFT_AVVIK_REGISTERINNTEKT',
    /**
     * RAPPORTER_INNTEKT
     */
    RAPPORTER_INNTEKT = 'RAPPORTER_INNTEKT',
    /**
     * SØK_YTELSE
     */
    SØK_YTELSE = 'SØK_YTELSE',
}

export type UngBrukerdialogKontraktOppgaverOppgavetypeDataDto = (
    | ({
          type: 'ENDRET_PERIODE';
      } & UngBrukerdialogKontraktOppgaverTyperEndretperiodeEndretPeriodeDataDto)
    | ({
          type: 'ENDRET_SLUTTDATO';
      } & UngBrukerdialogKontraktOppgaverTyperEndretsluttdatoEndretSluttdatoDataDto)
    | ({
          type: 'ENDRET_STARTDATO';
      } & UngBrukerdialogKontraktOppgaverTyperEndretstartdatoEndretStartdatoDataDto)
    | ({
          type: 'FJERNET_PERIODE';
      } & UngBrukerdialogKontraktOppgaverTyperFjernperiodeFjernetPeriodeDataDto)
    | ({
          type: 'INNTEKTSRAPPORTERING';
      } & UngBrukerdialogKontraktOppgaverTyperInntektsrapporteringInntektsrapporteringOppgavetypeDataDto)
    | ({
          type: 'KONTROLLER_REGISTERINNTEKT';
      } & UngBrukerdialogKontraktOppgaverTyperKontrollerregisterinntektKontrollerRegisterinntektOppgavetypeDataDto)
    | ({
          type: 'SØK_YTELSE';
      } & UngBrukerdialogKontraktOppgaverTyperSøkytelseSøkYtelseOppgavetypeDataDto)
) & {
    type: string;
};

export type UngBrukerdialogKontraktOppgaverSvarPåVarselDto = {
    harUttalelse: boolean;
    uttalelseFraBruker?: string;
};

export type UngBrukerdialogKontraktOppgaverTyperEndretperiodeEndretPeriodeDataDto = {
    endringer: UngBrukerdialogKontraktOppgaverTyperEndretperiodePeriodeEndringType[];
    forrigePeriode?: UngBrukerdialogKontraktOppgaverTyperEndretperiodePeriodeDto;
    nyPeriode?: UngBrukerdialogKontraktOppgaverTyperEndretperiodePeriodeDto;
};

export type UngBrukerdialogKontraktOppgaverTyperEndretperiodePeriodeDto = {
    fomDato?: string;
    tomDato?: string;
};

export enum UngBrukerdialogKontraktOppgaverTyperEndretperiodePeriodeEndringType {
    /**
     * ENDRET_STARTDATO
     */
    ENDRET_STARTDATO = 'ENDRET_STARTDATO',
    /**
     * ENDRET_SLUTTDATO
     */
    ENDRET_SLUTTDATO = 'ENDRET_SLUTTDATO',
    /**
     * FJERNET_PERIODE
     */
    FJERNET_PERIODE = 'FJERNET_PERIODE',
    /**
     * ANDRE_ENDRINGER
     */
    ANDRE_ENDRINGER = 'ANDRE_ENDRINGER',
}

export type UngBrukerdialogKontraktOppgaverTyperEndretsluttdatoEndretSluttdatoDataDto = {
    forrigeSluttdato?: string;
    nySluttdato: string;
};

export type UngBrukerdialogKontraktOppgaverTyperEndretstartdatoEndretStartdatoDataDto = {
    forrigeStartdato: string;
    nyStartdato: string;
};

export type UngBrukerdialogKontraktOppgaverTyperFjernperiodeFjernetPeriodeDataDto = {
    forrigeSluttdato?: string;
    forrigeStartdato: string;
};

export type UngBrukerdialogKontraktOppgaverTyperInntektsrapporteringInntektsrapporteringOppgavetypeDataDto = {
    fraOgMed: string;
    gjelderDelerAvMåned: boolean;
    tilOgMed: string;
};

export type UngBrukerdialogKontraktOppgaverTyperInntektsrapporteringRapportertInntektDto = {
    arbeidstakerOgFrilansInntekt: number;
    fraOgMed: string;
    tilOgMed: string;
};

export type UngBrukerdialogKontraktOppgaverTyperKontrollerregisterinntektArbeidOgFrilansRegisterInntektDto = {
    arbeidsgiver?: string;
    arbeidsgiverIdentifikator: string;
    arbeidsgiverNavn?: string;
    inntekt: number;
};

export type UngBrukerdialogKontraktOppgaverTyperKontrollerregisterinntektKontrollerRegisterinntektOppgavetypeDataDto = {
    fraOgMed: string;
    gjelderDelerAvMåned: boolean;
    registerinntekt: UngBrukerdialogKontraktOppgaverTyperKontrollerregisterinntektRegisterinntektDto;
    tilOgMed: string;
};

export type UngBrukerdialogKontraktOppgaverTyperKontrollerregisterinntektRegisterinntektDto = {
    arbeidOgFrilansInntekter?: UngBrukerdialogKontraktOppgaverTyperKontrollerregisterinntektArbeidOgFrilansRegisterInntektDto[];
    totalInntekt: number;
    totalInntektArbeidOgFrilans: number;
    totalInntektYtelse: number;
    ytelseInntekter?: UngBrukerdialogKontraktOppgaverTyperKontrollerregisterinntektYtelseRegisterInntektDto[];
};

export type UngBrukerdialogKontraktOppgaverTyperKontrollerregisterinntektYtelseRegisterInntektDto = {
    inntekt: number;
    ytelsetype: UngBrukerdialogKontraktOppgaverTyperKontrollerregisterinntektYtelseType;
};

export enum UngBrukerdialogKontraktOppgaverTyperKontrollerregisterinntektYtelseType {
    /**
     * DAGPENGER
     */
    DAGPENGER = 'DAGPENGER',
    /**
     * SYKEPENGER
     */
    SYKEPENGER = 'SYKEPENGER',
    /**
     * FORELDREPENGER
     */
    FORELDREPENGER = 'FORELDREPENGER',
    /**
     * PLEIEPENGER
     */
    PLEIEPENGER = 'PLEIEPENGER',
    /**
     * OMSORGSPENGER
     */
    OMSORGSPENGER = 'OMSORGSPENGER',
    /**
     * OPPLÆRINGSPENGER
     */
    OPPLÆRINGSPENGER = 'OPPLÆRINGSPENGER',
    /**
     * AAP
     */
    AAP = 'AAP',
    /**
     * ANNET
     */
    ANNET = 'ANNET',
}

export type UngBrukerdialogKontraktOppgaverTyperSøkytelseSøkYtelseOppgavetypeDataDto = {
    fomDato: string;
};

export type HentAlleOppgaverData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ekstern/api/oppgave/hent/alle';
};

export type HentAlleOppgaverResponses = {
    /**
     * default response
     */
    default: UngBrukerdialogKontraktOppgaverBrukerdialogOppgaveDto[];
};

export type HentAlleOppgaverResponse = HentAlleOppgaverResponses[keyof HentAlleOppgaverResponses];

export type HentOppgaveData = {
    body?: never;
    path: {
        /**
         * Unik referanse til oppgaven
         */
        oppgavereferanse: string;
    };
    query?: never;
    url: '/ekstern/api/oppgave/{oppgavereferanse}';
};

export type HentOppgaveResponses = {
    /**
     * default response
     */
    default: UngBrukerdialogKontraktOppgaverBrukerdialogOppgaveDto;
};

export type HentOppgaveResponse = HentOppgaveResponses[keyof HentOppgaveResponses];
