// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zOppgaveStatus = z.enum(['LØST', 'ULØST', 'AVBRUTT', 'UTLØPT']);

export const zOppgaveType = z.enum([
    'BEKREFT_ENDRET_STARTDATO',
    'BEKREFT_ENDRET_SLUTTDATO',
    'BEKREFT_ENDRET_PERIODE',
    'BEKREFT_FJERNET_PERIODE',
    'BEKREFT_AVVIK_REGISTERINNTEKT',
    'RAPPORTER_INNTEKT',
    'SØK_YTELSE',
]);

export const zSvarPåVarselDto = z.object({
    harUttalelse: z.boolean(),
    uttalelseFraBruker: z
        .string()
        .min(0)
        .max(4000)

        .optional(),
});

export const zEndretperiodePeriodeDto = z.object({
    fomDato: z.iso.date().optional(),
    tomDato: z.iso.date().optional(),
});

export const zEndretperiodePeriodeEndringType = z.enum([
    'ENDRET_STARTDATO',
    'ENDRET_SLUTTDATO',
    'FJERNET_PERIODE',
    'ANDRE_ENDRINGER',
]);

export const zEndretperiodeEndretPeriodeDataDto = z.object({
    endringer: z.array(zEndretperiodePeriodeEndringType).min(0).max(4),
    forrigePeriode: zEndretperiodePeriodeDto.optional(),
    nyPeriode: zEndretperiodePeriodeDto.optional(),
});

export const zEndretsluttdatoEndretSluttdatoDataDto = z.object({
    forrigeSluttdato: z.iso.date().optional(),
    nySluttdato: z.iso.date(),
});

export const zEndretstartdatoEndretStartdatoDataDto = z.object({
    forrigeStartdato: z.iso.date(),
    nyStartdato: z.iso.date(),
});

export const zFjernperiodeFjernetPeriodeDataDto = z.object({
    forrigeSluttdato: z.iso.date().optional(),
    forrigeStartdato: z.iso.date(),
});

export const zInntektsrapporteringInntektsrapporteringOppgavetypeDataDto = z.object({
    fraOgMed: z.iso.date(),
    gjelderDelerAvMåned: z.boolean(),
    tilOgMed: z.iso.date(),
});

export const zInntektsrapporteringRapportertInntektDto = z.object({
    arbeidstakerOgFrilansInntekt: z.number().gte(0).lte(999999),
    fraOgMed: z.iso.date(),
    tilOgMed: z.iso.date(),
});

export const zBekreftelseDto = z.intersection(
    z.union([
        z
            .object({
                type: z.literal('VARSEL_SVAR'),
            })
            .and(zSvarPåVarselDto),
        z
            .object({
                type: z.literal('RAPPORTERT_INNTEKT'),
            })
            .and(zInntektsrapporteringRapportertInntektDto),
    ]),
    z.object({
        type: z.string(),
    }),
);

export const zKontrollerregisterinntektArbeidOgFrilansRegisterInntektDto = z.object({
    arbeidsgiver: z.string().optional(),
    arbeidsgiverIdentifikator: z.string(),
    arbeidsgiverNavn: z.string().optional(),
    inntekt: z
        .int()
        .min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' })
        .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
});

export const zKontrollerregisterinntektYtelseType = z.enum([
    'DAGPENGER',
    'SYKEPENGER',
    'FORELDREPENGER',
    'PLEIEPENGER',
    'OMSORGSPENGER',
    'OPPLÆRINGSPENGER',
    'AAP',
    'ANNET',
]);

export const zKontrollerregisterinntektYtelseRegisterInntektDto = z.object({
    inntekt: z
        .int()
        .min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' })
        .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    ytelsetype: zKontrollerregisterinntektYtelseType,
});

export const zKontrollerregisterinntektRegisterinntektDto = z.object({
    arbeidOgFrilansInntekter: z
        .array(zKontrollerregisterinntektArbeidOgFrilansRegisterInntektDto)
        .min(0)
        .max(100)
        .optional(),
    totalInntekt: z
        .int()
        .min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' })
        .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    totalInntektArbeidOgFrilans: z
        .int()
        .min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' })
        .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    totalInntektYtelse: z
        .int()
        .min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' })
        .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    ytelseInntekter: z.array(zKontrollerregisterinntektYtelseRegisterInntektDto).min(0).max(100).optional(),
});

export const zKontrollerregisterinntektKontrollerRegisterinntektOppgavetypeDataDto = z.object({
    fraOgMed: z.iso.date(),
    gjelderDelerAvMåned: z.boolean(),
    registerinntekt: zKontrollerregisterinntektRegisterinntektDto,
    tilOgMed: z.iso.date(),
});

export const zSøkytelseSøkYtelseOppgavetypeDataDto = z.object({
    fomDato: z.iso.date(),
});

export const zOppgavetypeDataDto = z.intersection(
    z.union([
        z
            .object({
                type: z.literal('ENDRET_PERIODE'),
            })
            .and(zEndretperiodeEndretPeriodeDataDto),
        z
            .object({
                type: z.literal('ENDRET_SLUTTDATO'),
            })
            .and(zEndretsluttdatoEndretSluttdatoDataDto),
        z
            .object({
                type: z.literal('ENDRET_STARTDATO'),
            })
            .and(zEndretstartdatoEndretStartdatoDataDto),
        z
            .object({
                type: z.literal('FJERNET_PERIODE'),
            })
            .and(zFjernperiodeFjernetPeriodeDataDto),
        z
            .object({
                type: z.literal('INNTEKTSRAPPORTERING'),
            })
            .and(zInntektsrapporteringInntektsrapporteringOppgavetypeDataDto),
        z
            .object({
                type: z.literal('KONTROLLER_REGISTERINNTEKT'),
            })
            .and(zKontrollerregisterinntektKontrollerRegisterinntektOppgavetypeDataDto),
        z
            .object({
                type: z.literal('SØK_YTELSE'),
            })
            .and(zSøkytelseSøkYtelseOppgavetypeDataDto),
    ]),
    z.object({
        type: z.string(),
    }),
);

export const zBrukerdialogOppgaveDto = z.object({
    bekreftelse: zBekreftelseDto.optional(),
    frist: z.iso.datetime({ local: true }).optional(),
    løstDato: z.iso.datetime({ local: true }).optional(),
    oppgaveReferanse: z.uuid(),
    oppgavetype: zOppgaveType,
    oppgavetypeData: zOppgavetypeDataDto,
    opprettetDato: z.iso.datetime({ local: true }),
    status: zOppgaveStatus,
});

export const zHentAlleOppgaverData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional(),
});

/**
 * default response
 */
export const zHentAlleOppgaverResponse = z.array(zBrukerdialogOppgaveDto);

export const zHentOppgaveData = z.object({
    body: z.never().optional(),
    path: z.object({
        oppgavereferanse: z.uuid(),
    }),
    query: z.never().optional(),
});

/**
 * default response
 */
export const zHentOppgaveResponse = zBrukerdialogOppgaveDto;
