// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zUngBrukerdialogKontraktOppgaverOppgaveStatus = z.enum(['LØST', 'ULØST', 'AVBRUTT', 'UTLØPT']);

export const zUngBrukerdialogKontraktOppgaverOppgaveType = z.enum([
    'BEKREFT_ENDRET_STARTDATO',
    'BEKREFT_ENDRET_SLUTTDATO',
    'BEKREFT_ENDRET_PERIODE',
    'BEKREFT_FJERNET_PERIODE',
    'BEKREFT_AVVIK_REGISTERINNTEKT',
    'RAPPORTER_INNTEKT',
    'SØK_YTELSE',
]);

export const zUngBrukerdialogKontraktOppgaverSvarPåVarselDto = z.object({
    harUttalelse: z.boolean(),
    uttalelseFraBruker: z.string().min(0).max(4000).optional(),
});

export const zUngBrukerdialogKontraktOppgaverTyperEndretperiodePeriodeDto = z.object({
    fomDato: z.iso.date().optional(),
    tomDato: z.iso.date().optional(),
});

export const zUngBrukerdialogKontraktOppgaverTyperEndretperiodePeriodeEndringType = z.enum([
    'ENDRET_STARTDATO',
    'ENDRET_SLUTTDATO',
    'FJERNET_PERIODE',
    'ANDRE_ENDRINGER',
]);

export const zUngBrukerdialogKontraktOppgaverTyperEndretperiodeEndretPeriodeDataDto = z.object({
    endringer: z.array(zUngBrukerdialogKontraktOppgaverTyperEndretperiodePeriodeEndringType).min(0).max(4),
    forrigePeriode: zUngBrukerdialogKontraktOppgaverTyperEndretperiodePeriodeDto.optional(),
    nyPeriode: zUngBrukerdialogKontraktOppgaverTyperEndretperiodePeriodeDto.optional(),
});

export const zUngBrukerdialogKontraktOppgaverTyperEndretsluttdatoEndretSluttdatoDataDto = z.object({
    forrigeSluttdato: z.iso.date().optional(),
    nySluttdato: z.iso.date(),
});

export const zUngBrukerdialogKontraktOppgaverTyperEndretstartdatoEndretStartdatoDataDto = z.object({
    forrigeStartdato: z.iso.date(),
    nyStartdato: z.iso.date(),
});

export const zUngBrukerdialogKontraktOppgaverTyperFjernperiodeFjernetPeriodeDataDto = z.object({
    forrigeSluttdato: z.iso.date().optional(),
    forrigeStartdato: z.iso.date(),
});

export const zUngBrukerdialogKontraktOppgaverTyperInntektsrapporteringInntektsrapporteringOppgavetypeDataDto = z.object(
    {
        fraOgMed: z.iso.date(),
        gjelderDelerAvMåned: z.boolean(),
        tilOgMed: z.iso.date(),
    },
);

export const zUngBrukerdialogKontraktOppgaverTyperInntektsrapporteringRapportertInntektDto = z.object({
    arbeidstakerOgFrilansInntekt: z.number().gte(0).lte(999999),
    fraOgMed: z.iso.date(),
    tilOgMed: z.iso.date(),
});

export const zUngBrukerdialogKontraktOppgaverBekreftelseDto = z.intersection(
    z.union([
        z
            .object({
                type: z.literal('VARSEL_SVAR'),
            })
            .and(zUngBrukerdialogKontraktOppgaverSvarPåVarselDto),
        z
            .object({
                type: z.literal('RAPPORTERT_INNTEKT'),
            })
            .and(zUngBrukerdialogKontraktOppgaverTyperInntektsrapporteringRapportertInntektDto),
    ]),
    z.object({
        type: z.string(),
    }),
);

export const zUngBrukerdialogKontraktOppgaverTyperKontrollerregisterinntektArbeidOgFrilansRegisterInntektDto = z.object(
    {
        arbeidsgiver: z.string().optional(),
        arbeidsgiverIdentifikator: z.string(),
        arbeidsgiverNavn: z.string().optional(),
        inntekt: z
            .int()
            .min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' })
            .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    },
);

export const zUngBrukerdialogKontraktOppgaverTyperKontrollerregisterinntektYtelseType = z.enum([
    'DAGPENGER',
    'SYKEPENGER',
    'FORELDREPENGER',
    'PLEIEPENGER',
    'OMSORGSPENGER',
    'OPPLÆRINGSPENGER',
    'AAP',
    'ANNET',
]);

export const zUngBrukerdialogKontraktOppgaverTyperKontrollerregisterinntektYtelseRegisterInntektDto = z.object({
    inntekt: z
        .int()
        .min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' })
        .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    ytelsetype: zUngBrukerdialogKontraktOppgaverTyperKontrollerregisterinntektYtelseType,
});

export const zUngBrukerdialogKontraktOppgaverTyperKontrollerregisterinntektRegisterinntektDto = z.object({
    arbeidOgFrilansInntekter: z
        .array(zUngBrukerdialogKontraktOppgaverTyperKontrollerregisterinntektArbeidOgFrilansRegisterInntektDto)
        .min(0)
        .max(100)
        .optional(),
    totalInntekt: z
        .int()
        .min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' })
        .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    totalInntektArbeidOgFrilans: z
        .int()
        .min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' })
        .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    totalInntektYtelse: z
        .int()
        .min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' })
        .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    ytelseInntekter: z
        .array(zUngBrukerdialogKontraktOppgaverTyperKontrollerregisterinntektYtelseRegisterInntektDto)
        .min(0)
        .max(100)
        .optional(),
});

export const zUngBrukerdialogKontraktOppgaverTyperKontrollerregisterinntektKontrollerRegisterinntektOppgavetypeDataDto =
    z.object({
        fraOgMed: z.iso.date(),
        gjelderDelerAvMåned: z.boolean(),
        registerinntekt: zUngBrukerdialogKontraktOppgaverTyperKontrollerregisterinntektRegisterinntektDto,
        tilOgMed: z.iso.date(),
    });

export const zUngBrukerdialogKontraktOppgaverTyperSøkytelseSøkYtelseOppgavetypeDataDto = z.object({
    fomDato: z.iso.date(),
});

export const zUngBrukerdialogKontraktOppgaverOppgavetypeDataDto = z.intersection(
    z.union([
        z
            .object({
                type: z.literal('ENDRET_PERIODE'),
            })
            .and(zUngBrukerdialogKontraktOppgaverTyperEndretperiodeEndretPeriodeDataDto),
        z
            .object({
                type: z.literal('ENDRET_SLUTTDATO'),
            })
            .and(zUngBrukerdialogKontraktOppgaverTyperEndretsluttdatoEndretSluttdatoDataDto),
        z
            .object({
                type: z.literal('ENDRET_STARTDATO'),
            })
            .and(zUngBrukerdialogKontraktOppgaverTyperEndretstartdatoEndretStartdatoDataDto),
        z
            .object({
                type: z.literal('FJERNET_PERIODE'),
            })
            .and(zUngBrukerdialogKontraktOppgaverTyperFjernperiodeFjernetPeriodeDataDto),
        z
            .object({
                type: z.literal('INNTEKTSRAPPORTERING'),
            })
            .and(zUngBrukerdialogKontraktOppgaverTyperInntektsrapporteringInntektsrapporteringOppgavetypeDataDto),
        z
            .object({
                type: z.literal('KONTROLLER_REGISTERINNTEKT'),
            })
            .and(
                zUngBrukerdialogKontraktOppgaverTyperKontrollerregisterinntektKontrollerRegisterinntektOppgavetypeDataDto,
            ),
        z
            .object({
                type: z.literal('SØK_YTELSE'),
            })
            .and(zUngBrukerdialogKontraktOppgaverTyperSøkytelseSøkYtelseOppgavetypeDataDto),
    ]),
    z.object({
        type: z.string(),
    }),
);

export const zUngBrukerdialogKontraktOppgaverBrukerdialogOppgaveDto = z.object({
    bekreftelse: zUngBrukerdialogKontraktOppgaverBekreftelseDto.optional(),
    frist: z.iso.datetime({ local: true }).optional(),
    løstDato: z.iso.datetime({ local: true }).optional(),
    oppgaveReferanse: z.uuid(),
    oppgavetype: zUngBrukerdialogKontraktOppgaverOppgaveType,
    oppgavetypeData: zUngBrukerdialogKontraktOppgaverOppgavetypeDataDto,
    opprettetDato: z.iso.datetime({ local: true }),
    status: zUngBrukerdialogKontraktOppgaverOppgaveStatus,
});

export const zHentAlleOppgaverData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional(),
});

/**
 * default response
 */
export const zHentAlleOppgaverResponse = z.array(zUngBrukerdialogKontraktOppgaverBrukerdialogOppgaveDto);

export const zHentOppgaveData = z.object({
    body: z.never().optional(),
    path: z.object({
        oppgavereferanse: z.uuid(),
    }),
    query: z.never().optional(),
});

/**
 * default response
 */
export const zHentOppgaveResponse = zUngBrukerdialogKontraktOppgaverBrukerdialogOppgaveDto;
