import { Attachment, PersistedFile } from '../../types/Attachment';
export declare const VALID_EXTENSIONS: string[];
export declare const MAX_FILESIZE_FOR_UPLOAD = 9999999;
export declare const MAX_TOTAL_ATTACHMENT_SIZE_IN_MB = 24;
export declare const MAX_TOTAL_ATTACHMENT_SIZE_BYTES: number;
export declare const getTotalSizeOfAttachments: (attachments: Attachment[]) => number;
export declare const fileExtensionIsValid: (filename: string) => boolean;
export declare const fileSizeIsValid: (size: number) => boolean;
export declare const isFileObject: (file: File | PersistedFile) => file is File;
export declare const mapFileToPersistedFile: ({ name, lastModified, type, size, ...rest }: File | PersistedFile) => PersistedFile;
export declare const getAttachmentFromFile: (file: File) => Attachment;
export declare const getPendingAttachmentFromFile: (file: File) => Attachment;
export declare const attachmentShouldBeProcessed: ({ pending, uploaded }: Attachment) => boolean;
export declare const attachmentShouldBeUploaded: (attachment: Attachment) => boolean;
export declare const attachmentUploadHasFailed: ({ pending, uploaded, file: { name } }: Attachment) => boolean;
export declare const attachmentHasBeenUploaded: ({ pending, uploaded, file: { name } }: Attachment) => boolean;
export declare const containsAnyUploadedAttachments: (attachmentList: Attachment[]) => boolean;
