export enum DineBarnScenario {
    INGEN_BARN = 'INGEN_BARN',
    ETT_ELLER_TO_UNDER_13 = 'ETT_ELLER_TO_UNDER_13',
    TRE_ELLER_FLERE_UNDER_13 = 'TRE_ELLER_FLERE_UNDER_13',
    KUN_OVER_13 = 'KUN_OVER_13',
}
