name: .Deploy application to dev

on:
    workflow_call:
        inputs:
            working-directory:
                type: string
                required: true
            app-name:
                type: string
                required: true
        secrets:
            NAIS_DEPLOY_APIKEY:
                description: Nais deploy APIKEY
                required: false

env:
    IMAGE: ghcr.io/${{ github.repository }}/${{ inputs.app-name }}-mono:${{ github.sha }}
    GITHUB_USERNAME: x-access-token
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    GITHUB_REF_NAME: ${{ github.ref_name }}

jobs:
    deploy-to-dev:
        name: Deploy ${{ inputs.app-name }} to dev (${{github.ref_name}})
        runs-on: ubuntu-latest
        permissions:
            packages: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'yarn'

            - name: Install dependencies (yarn)
              run: yarn

            - name: Run tests
              run: yarn test --filter=${{inputs.app-name}}

            - name: Build application
              run: |
                  yarn build-${{ inputs.app-name }}

            - name: Build and publish Docker image
              run: |
                  docker build -t ${IMAGE} -f apps/${{inputs.app-name}}/Dockerfile .
                  docker login ghcr.io -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
                  docker push ${IMAGE}

            - name: Deploy to dev
              uses: nais/deploy/actions/deploy@v1
              env:
                  CLUSTER: dev-gcp
                  RESOURCE: nais-config/nais.yml
                  VARS: apps/${{ inputs.app-name }}/nais/dev-gcp.json
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  GITHUB_REF_NAME: ${{ github.ref_name }}
