name: .Test-Deploy omssoknad distroless

on:
  workflow_dispatch:


jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required: nais/docker-build-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies (yarn)
        run: yarn

      - name: Build application
        run: yarn build-omsorgspengesoknad

      - name: Build with turbo
        run: yarn turbo run build-app --filter=@navikt/omsorgspengesoknad

      - name: Build and publish docker image
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: dusseldorf
          push_image: true
          pull: true
          dockerfile: Dockerfile
          docker_context: .
          build_args: APP_NAME=omsorgspengesoknad
          image_suffix: omsorgspengesoknad-test-mono
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais-config/nais.yml
          VARS: apps/omsorgspengesoknad/nais/dev-gcp.json
          VAR: GITHUB_REF_NAME=${{ github.ref_name }} # brukes i applikasjonerna
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          IMAGE: ${{ steps.docker-push.outputs.image }}
