name: app.common

on:
    workflow_call:
        inputs:
            working-directory:
                type: string
                required: true
            app-name:
                type: string
                required: true
        secrets:
            NAIS_DEPLOY_APIKEY:
                description: Nais deploy APIKEY
                required: false
env:
    IMAGE: docker.pkg.github.com/${{ github.repository }}/${{ inputs.app-name }}-mono:${{ github.sha }}
    GITHUB_USERNAME: x-access-token
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    build-and-test:
        name: Build and test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - name: Check out code
              uses: actions/checkout@v2
              with:
                  fetch-depth: 2

            - name: Setup Node.js environment
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install dependencies
              run: yarn

            - name: Build
              run: yarn build

            - name: Test
              run: yarn test

    build-code-and-push-docker:
        name: Build and push docker
        if: startsWith(github.ref, 'refs/heads/dev-') || startsWith(github.ref, 'refs/heads/main') || github.event.deployment.payload.triggered
        needs: build-and-test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  fetch-depth: 2

            - name: Cache node-modules
              uses: actions/cache@v2
              with:
                path: '**/node_modules'
                key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            # - name: Cache dependencies
            #   uses: actions/cache@v1
            #   with:
            #       path: node_modules
            #       key: ${{ runner.OS }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
            #       restore-keys: |
            #           ${{ runner.OS }}-yarn-cache-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Build code
              run: |
                  yarn
                  yarn build

            - name: Build and publish Docker image
              run: |
                  docker build -t ${IMAGE} -f ${{inputs.working-directory}}/Dockerfile .
                  docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
                  docker push ${IMAGE}

    deploy-dev-gcp:
        name: Deploy to dev-gcp
        if: startsWith(github.ref, 'refs/heads/dev-') || startsWith(github.ref, 'refs/heads/main')
        needs: build-code-and-push-docker
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  fetch-depth: 2
            - name: deploy
              uses: nais/deploy/actions/deploy@v1
              env:
                  CLUSTER: dev-gcp
                  RESOURCE: config/nais.yml
                  VARS: config/${{ inputs.app-name }}/dev-gcp.json
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
