name: app.endringsmelding-pleiepenger

on:
    push:
        paths:
            - 'apps/endringsmelding-pleiepenger/**/*'
            - 'nais-config/**/*'
            - 'packages/**/*'
            - .github/workflows/app.endringsmelding-pleiepenger.yml

env:
    APP_NAME: 'endringsmelding-pleiepenger'

jobs:
    run-script-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Installing pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 7.28.0

            - name: Set up NODE med pnpm
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  scope: '@navikt'
                  cache: 'pnpm'

            - name: Install dependencies (pnpm)
              run: pnpm install --frozen-lockfile

            - name: Build packages (pnpm)
              run: pnpm build-package

            - name: Run code tests
              run: pnpm test --filter=@navikt/endringsmelding-pleiepenger

    run-cypress-test:
        runs-on: ubuntu-latest
        container: cypress/included:12.7.0
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Installing pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 7.28.0

            - name: Set up NODE med pnpm
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  scope: '@navikt'
                  cache: 'pnpm'

            - name: Install dependencies (pnpm)
              run: pnpm install --frozen-lockfile

            - name: Run cypress tests
              uses: cypress-io/github-action@v5 # use the explicit version number
              env:
                  API_URL_INNSYN: http://localhost:8099
                  API_URL: http://localhost:8099
                  DEKORATOR_URL: https://www.nav.no/dekoratoren/?simple=true&chatbot=false
                  PUBLIC_PATH: /familie/sykdom-i-familien/soknad/endringsmelding-pleiepenger
                  MSW: off
                  APP_VERSION: dev
                  FRONTEND_API_PATH: http://localhost:8099/
                  FRONTEND_VEDLEGG_URL: http://localhost:8099/api
                  FRONTEND_INNSYN_API_PATH: http://localhost:8099/api
                  VELG_SAK: off
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  project: ./apps/endringsmelding-pleiepenger/e2e
                  build: pnpm build-endringsmelding-pleiepenger
                  start: pnpm e2e-endringsmelding-pleiepenger
                  record: true
