name: Copilot Setup Steps

on:
    workflow_dispatch:

jobs:
    copilot-setup-steps:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v7.0.1

            - uses: actions/setup-node@v7.0.0
              with:
                  node-version: 24

            - uses: pnpm/action-setup@v6
            - run: pnpm install --frozen-lockfile
              env:
                  NPM_TOKEN: ${{ secrets.READER_TOKEN }}
