name: Copilot Setup Steps

on:
    workflow_dispatch:

jobs:
    setup:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v6

            - uses: actions/setup-node@v6.4.0
              with:
                  node-version: 22

            - uses: pnpm/action-setup@v4
              with:
            - run: pnpm install --frozen-lockfile
              env:
                  NPM_TOKEN: ${{ secrets.READER_TOKEN }}
