name: Copilot Setup Steps

on:
    workflow_dispatch:

jobs:
    setup:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v6

            - uses: actions/setup-node@v6.4.0
              with:
                  node-version: 22

            - run: corepack enable
            - run: yarn install --immutable
