name: Deploy application to dev

on:
    workflow_call:
        inputs:
            working-directory:
                type: string
                required: true
            app-name:
                type: string
                required: true
        secrets:
            NAIS_DEPLOY_APIKEY:
                description: Nais deploy APIKEY
                required: false

env:
    IMAGE: ghcr.io/${{ github.repository }}/${{ inputs.app-name }}-mono:${{ github.sha }}
    GITHUB_USERNAME: x-access-token
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    deploy-to-dev:
        name: Deploy ${{ inputs.app-name }} to dev
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2
            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'npm'
            - name: Install dependencies
              run: npm i

            - name: Run tests
              run: npm run test

            - name: Build application
              run: |
                  npm run build-${{ inputs.app-name }}

            - name: Build and publish Docker image
              run: |
                  docker build -t ${IMAGE} -f apps/${{inputs.app-name}}/Dockerfile .
                  docker login ghcr.io -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
                  docker push ${IMAGE}

            - name: Deploy to dev
              uses: nais/deploy/actions/deploy@v1
              env:
                  CLUSTER: dev-gcp
                  RESOURCE: config/nais.yml
                  VARS: config/${{ inputs.app-name }}/dev-gcp.json
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
