name: Deploy app to prod

on:
  workflow_dispatch:
    inputs:
        app-name:
            description: Choose application
            type: choice
            options:
            - sif-ettersending
            required: true
    secrets:
        NAIS_DEPLOY_APIKEY:
            description: Nais deploy APIKEY
            required: false

jobs:
    deploy-to-prod:
        name: Deploy ${{ inputs.app-name }} to prod
        uses: navikt/sif-brukerdialog/.github/workflows/deploy-app-to-prod.yml@main
        secrets:
            NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        with:
            app-name: '${{ inputs.app-name }}'
            working-directory: 'apps/${{ inputs.app-name }}'
