name: Deploy app to demo
run-name: Deploy ${{ inputs.app-name }} to demo (${{github.ref_name}})

on:
    workflow_dispatch:
        inputs:
            app-name:
                description: Choose application
                type: choice
                options:
                    - opplaringspenger-soknad
                required: true

jobs:
    deploy-to-demo:
        name: Deploy ${{ inputs.app-name }} to demo
        uses: navikt/sif-brukerdialog/.github/workflows/.deploy-app-to-demo.yml@main
        secrets: inherit
        permissions:
            id-token: write
        with:
            app-name: '${{ inputs.app-name }}'
            working-directory: 'apps/${{ inputs.app-name }}'
