name: Changeset release - build PR

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: "write"
      pull-requests: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .yarnrc.yml
        run: |
            yarn config set npmScopes.navikt.npmRegistryServer "https://npm.pkg.github.com"
            yarn config set npmScopes.navikt.npmAlwaysAuth true
            yarn config set npmScopes.navikt.npmAuthToken $NODE_AUTH_TOKEN
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
