name: Cypress Tests

on:
    workflow_call:
        inputs:
            PUBLIC_PATH:
                type: string
                required: true
            app-name:
                type: string
                required: true

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run application cypress tests
        uses: cypress-io/github-action@v4 # use the explicit version number
        env:
          DEKORATOR_URL: https://www.nav.no/dekoratoren/?simple=true&chatbot=false
          PUBLIC_PATH: ${{ inputs.PUBLIC_PATH }}
        with:
            project: ./apps/${{ inputs.app-name }}/e2e
            build: yarn build-${{ inputs.app-name }}
            start: yarn e2e-${{ inputs.app-name }}
