# This workflow trigger on push to apps/sif-ettersending
name: test.ungdomsytelse-deltaker
on:
    push:
        branches-ignore:
            - 'main'
        paths:
            - 'apps/ungdomsytelse-deltaker/**/*'
            - 'nais-config/**/*'
            - 'packages/**/*'
            - .github/workflows/test.ungdomsytelse-deltaker.yml
            - .github/workflows/.sonarcloud.app-scan.yml
            - yarn.lock

    workflow_call:
    workflow_dispatch:

env:
    APP_NAME: 'ungdomsytelse-deltaker'

permissions:
    contents: read

jobs:
    run-script-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup .yarnrc.yml
              run: |
                  yarn config set npmScopes.navikt.npmRegistryServer "https://npm.pkg.github.com"
                  yarn config set npmScopes.navikt.npmAlwaysAuth true
                  yarn config set npmScopes.navikt.npmAuthToken $NODE_AUTH_TOKEN
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

            - name: Setup Node.js environment
              uses: actions/setup-node@v6
              with:
                  node-version: 22
                  cache: 'yarn'
            - run: yarn set version 4.x

            - name: Install dependencies (yarn)
              run: yarn

            - name: Run code tests
              run: yarn turbo test --filter=@navikt/ungdomsytelse-deltaker

    run-playwright-test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup .yarnrc.yml
              run: |
                  yarn config set npmScopes.navikt.npmRegistryServer "https://npm.pkg.github.com"
                  yarn config set npmScopes.navikt.npmAlwaysAuth true
                  yarn config set npmScopes.navikt.npmAuthToken $NODE_AUTH_TOKEN
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

            - name: Setup Node.js environment
              uses: actions/setup-node@v6
              with:
                  node-version: 22
                  cache: 'yarn'
            - run: yarn set version 4.x

            - name: Install dependencies
              run: yarn

            - name: Install Playwright Browsers
              run: npx playwright install chromium

            - name: Build application for testing
              run: yarn turbo e2e:build --filter=@navikt/ungdomsytelse-deltaker

            - name: Run tests
              run: yarn turbo playwright-test --filter=@navikt/ungdomsytelse-deltaker

    sonar:
        uses: ./.github/workflows/.sonarcloud.app-scan.yml
        with:
            app: ungdomsytelse-deltaker
            working-directory: 'apps/ungdomsytelse-deltaker'
        secrets: inherit
