name: Test app on change

on:
    push:
        branches-ignore:
            - 'main'
        paths:
            - 'apps/**/*'
            - 'nais-config/**/*'
            - 'packages/**/*'
            - .github/workflows/**/*
    workflow_call:

jobs:
    shared-code-env:
        runs-on: ubuntu-latest
        steps:
            - name: set shared-code-change env
              run: |
                if (contains(github.event_path, 'nais-config') ||
                    contains(github.event_path, 'packages') ||
                    contains(github.event_path, 'workflows')) {
                        echo "{IS_SHARED_CODE_CHANGE}={true}" >> "$GITHUB_ENV"
                    } else {
                        echo "{IS_SHARED_CODE_CHANGE}={false}" >> "$GITHUB_ENV"
                    }


    test-ekstra-omsorgsdager-annen-forelder-ikke-tilsyn:
        needs: shared-code-env
        runs-on: ubuntu-latest
        if: env.IS_SHARED_CODE_CHANGE == 'true' || contains(github.event_path, 'ekstra-omsorgsdager-andre-forelder-ikke-tilsyn')
        steps:
            - name: test-ekstra-omsorgsdager-annen-forelder-ikke-tilsyn
              uses: ./.github/workflows/test.app.yml
              with:
                 app-name: 'test.ekstra-omsorgsdager-andre-forelder-ikke-tilsyn'

    # test-endringsmelding-pleiepenger:
    #   uses: ./.github/workflows/test.app.yml
    #   if: env.IS_SHARED_CODE_CHANGE == true || contains(github.event_path, 'ekstra-omsorgsdager-andre-forelder-ikke-tilsyn/')
    #   secrets: inherit
    #   with:
    #     app-name: 'endringsmelding-pleiepenger'

    # test-omsorgsdager-aleneomsorg:
    #   uses: ./.github/workflows/test.app.yml
    #   if: env.IS_SHARED_CODE_CHANGE == true || contains(github.event_path, 'omsorgsdager-aleneomsorg')
    #   secrets: inherit
    #   with:
    #     app-name: 'omsorgsdager-aleneomsorg'
