name: Test en eller alle applikasjoner

on:
    workflow_call:
        inputs:
            app-name:
                description: 'App som skal testes. Evt. ingen for å teste alle'
                required: false
                default: ''
                type: string

    workflow_dispatch:
        inputs:
            app-name:
                description: 'App som skal testes. Evt. ingen for å teste alle'
                required: false
                default: ''
                type: string

    push:
        branches:
            - '*workflows'

env:
    NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

permissions:
    contents: read

jobs:
    test-apps:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup .yarnrc.yml
              run: |
                  yarn config set npmScopes.navikt.npmRegistryServer "https://npm.pkg.github.com"
                  yarn config set npmScopes.navikt.npmAlwaysAuth true
                  yarn config set npmScopes.navikt.npmAuthToken $NODE_AUTH_TOKEN

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: 'yarn'
            - run: yarn set version 4.x

            - name: Install dependencies
              run: yarn

            - name: Install Playwright Browsers
              run: npx playwright install chromium

            # Steps for each app
            - name: Run tests for dine-pleiepenger
              if: ${{ inputs.app-name == '' || inputs.app-name == 'dine-pleiepenger' }}
              run: |
                  yarn test --filter=@navikt/dine-pleiepenger
                  yarn turbo playwright-test --filter=@navikt/dine-pleiepenger

            - name: Run tests for ekstra-omsorgsdager-andre-forelder-ikke-tilsyn
              if: ${{ inputs.app-name == '' || inputs.app-name == 'ekstra-omsorgsdager-andre-forelder-ikke-tilsyn' }}
              run: |
                  yarn test --filter=@navikt/ekstra-omsorgsdager-andre-forelder-ikke-tilsyn
                  yarn turbo playwright-test --filter=@navikt/ekstra-omsorgsdager-andre-forelder-ikke-tilsyn

            - name: Run tests for endringsmelding-pleiepenger
              if: ${{ inputs.app-name == '' || inputs.app-name == 'endringsmelding-pleiepenger' }}
              run: |
                  yarn test --filter=@navikt/endringsmelding-pleiepenger
                  yarn turbo playwright-test --filter=@navikt/endringsmelding-pleiepenger

            # Legg til flere steg for andre apper på samme måte
