name: test.opplaringspenger-søknad

on:
    push:
        branches-ignore:
            - 'main'
        paths:
            - 'apps/opplaringspenger-soknad/**/*'
            - 'nais-config/**/*'
            - 'packages/**/*'
            - .github/workflows/test.opplaringpenger-soknad.yml
            - yarn.lock

    workflow_call:

env:
    APP_NAME: 'opplaringspenger-soknad'

permissions:
    contents: read

jobs:
    run-script-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup .yarnrc.yml
              run: |
                  yarn config set npmScopes.navikt.npmRegistryServer "https://npm.pkg.github.com"
                  yarn config set npmScopes.navikt.npmAlwaysAuth true
                  yarn config set npmScopes.navikt.npmAuthToken $NODE_AUTH_TOKEN
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

            - name: Setup Node.js environment
              uses: actions/setup-node@v5
              with:
                  node-version: 22
                  cache: 'yarn'
            - run: yarn set version 4.x

            - name: Install dependencies (yarn)
              run: yarn

            - name: Run code tests
              run: yarn test --filter=@navikt/opplaringspenger-soknad

    run-playwright-test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup .yarnrc.yml
              run: |
                  yarn config set npmScopes.navikt.npmRegistryServer "https://npm.pkg.github.com"
                  yarn config set npmScopes.navikt.npmAlwaysAuth true
                  yarn config set npmScopes.navikt.npmAuthToken $NODE_AUTH_TOKEN
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

            - name: Setup Node.js environment
              uses: actions/setup-node@v5
              with:
                  node-version: 22
                  cache: 'yarn'
            - run: yarn set version 4.x

            - name: Install dependencies
              run: yarn

            - name: Install Playwright Browsers
              run: npx playwright install chromium

            - name: Build and run tests
              run: yarn turbo playwright-test --filter=@navikt/opplaringspenger-soknad
