name: Test en eller alle applikasjoner

on:
    workflow_call:
        inputs:
            app-name:
                description: 'App som skal testes. Evt. ingen for å teste alle'
                required: false
                default: ''
                type: string

    workflow_dispatch:
        inputs:
            app-name:
                description: 'App som skal testes. Evt. ingen for å teste alle'
                required: false
                default: ''
                type: string

    push:
        branches:
            - '*workflows'

env:
    NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
    APP_LIST: |
        [
          "dine-pleiepenger",
          "ekstra-omsorgsdager-andre-forelder-ikke-tilsyn",
          "endringsmelding-pleiepenger",
          "omsorgsdager-aleneomsorg-dialog",
          "omsorgsdager-kalkulator",
          "omsorgspengerutbetaling-arbeidstaker-soknad",
          "omsorgspengerutbetaling-soknad",
          "omsorgspengesoknad",
          "opplaringspenger-soknad",
          "pleiepenger-i-livets-sluttfase-soknad",
          "pleiepenger-sykt-barn",
          "sif-ettersending"
        ]

permissions:
    contents: read

jobs:
    setup-environment:
        name: Setup Environment
        runs-on: ubuntu-latest
        outputs:
            workspace-path: ${{ steps.upload-workspace.outputs.artifact-path }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Cache dependencies
              id: cache-deps
              uses: actions/cache@v3
              with:
                  path: |
                      node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-modules-

            - name: Setup [.yarnrc.yml](http://_vscodecontentref_/2)
              run: |
                  yarn config set npmScopes.navikt.npmRegistryServer "https://npm.pkg.github.com"
                  yarn config set npmScopes.navikt.npmAlwaysAuth true
                  yarn config set npmScopes.navikt.npmAuthToken $NODE_AUTH_TOKEN

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: 'yarn'
            - run: yarn set version 4.x

            - name: Install dependencies
              run: yarn

            - name: Install Playwright Browsers
              run: npx playwright install chromium

            - name: Upload workspace
              id: upload-workspace
              uses: actions/upload-artifact@v3
              with:
                  name: workspace
                  path: |
                      node_modules
                      .yarn
                      .pnp.*

    test-apps:
        name: Run Tests
        needs: setup-environment
        runs-on: ubuntu-latest
        strategy:
            matrix:
                app: ${{ fromJson('["dine-pleiepenger", "ekstra-omsorgsdager-andre-forelder-ikke-tilsyn",]') }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Download workspace
              uses: actions/download-artifact@v3
              with:
                  name: workspace

            - name: Run code tests
              run: yarn test --filter=@navikt/${{ matrix.app }}

            - name: Run Playwright tests
              run: yarn turbo playwright-test  matrix--filter=@navikt/${{matrix.app }}
