# This workflow trigger on push to apps/sif-ettersending
name: test.ettersending
on:
    push:
        paths:
            - 'apps/sif-ettersending/**/*'
            - 'nais-config/**/*'
            - 'packages/**/*'
            - .github/workflows/app.sif-ettersending.yml
            - .github/workflows/test.sif-ettersending.yml

env:
    APP_NAME: 'ettersending'

jobs:
    run-script-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'yarn'

            - name: Install dependencies (yarn)
              run: yarn

            - name: Run code tests
              run: yarn test --filter=sif-ettersending

    run-cypress-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'yarn'

            - name: Build and start e2e server
              uses: cypress-io/github-action@v5
              env:
                  API_URL: http://localhost:8089/
                  FRONTEND_API_PATH: http://localhost:8089/
                  FRONTEND_VEDLEGG_URL: https://k9-ettersending-soknad.intern.dev.nav.no/api
                  LIVETS_SLUTTFASE: on
                  NPM_CONFIG_CACHE: /tmp
                  PUBLIC_PATH: /familie/sykdom-i-familien/soknad/ettersending
              with:
                  project: ./apps/sif-ettersending/e2e
                  build: yarn build-sif-ettersending
                  start: yarn turbo start-e2e-server --filter=sif-ettersending
                  wait-on: 'http://localhost:8080'
                  wait-on-timeout: 60
                  runTests: false
            - name: Run cypress tests
              run: yarn turbo cypress-run --filter=sif-ettersending
