name: Test en eller alle applikasjoner

on:
    workflow_call:
        inputs:
            app-name:
                description: 'App som skal testes. Evt. ingen for å teste alle'
                required: false
                default: env.APP_LIST
                type: string

    workflow_dispatch:
        inputs:
            app-name:
                description: 'App som skal testes. Evt. ingen for å teste alle'
                required: false
                default: env.APP_LIST
                type: string

    push:
        branches:
            - '*workflows'

env:
    NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
    APP_LIST: |
        [
          "dine-pleiepenger",
          "ekstra-omsorgsdager-andre-forelder-ikke-tilsyn",
          "endringsmelding-pleiepenger",
          "omsorgsdager-aleneomsorg-dialog",
          "omsorgsdager-kalkulator",
          "omsorgspengerutbetaling-arbeidstaker-soknad",
          "omsorgspengerutbetaling-soknad",
          "omsorgspengesoknad",
          "opplaringspenger-soknad",
          "pleiepenger-i-livets-sluttfase-soknad",
          "pleiepenger-sykt-barn",
          "sif-ettersending",
        ]

permissions:
    contents: read

jobs:
    test-apps:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                app: ${{ fromJson('["dine-pleiepenger", "ekstra-omsorgsdager-andre-forelder-ikke-tilsyn",]') }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup .yarnrc.yml
              run: |
                  yarn config set npmScopes.navikt.npmRegistryServer "https://npm.pkg.github.com"
                  yarn config set npmScopes.navikt.npmAlwaysAuth true
                  yarn config set npmScopes.navikt.npmAuthToken $NODE_AUTH_TOKEN

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: 'yarn'
            - run: yarn set version 4.x

            - name: Install dependencies
              run: yarn

            - name: Install Playwright Browsers
              run: npx playwright install chromium

            - name: Run code tests
              run: yarn test --filter=@navikt/${{ matrix.app }}

            - name: Run Playwright tests
              run: yarn turbo playwright-test --filter=@navikt/${{ matrix.app }}
