// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
    AktiverMikrofrontendData,
    AktiverMikrofrontendErrors,
    AktiverMikrofrontendResponses,
    HentDokumentData,
    HentDokumentErrors,
    HentDokumentOversiktData,
    HentDokumentOversiktErrors,
    HentDokumentOversiktResponses,
    HentDokumentResponses,
    HentMikrofrontenderData,
    HentMikrofrontenderErrors,
    HentMikrofrontenderResponses,
    HentSøknadData,
    HentSøknader1Data,
    HentSøknader1Errors,
    HentSøknader1Responses,
    HentSøknaderData,
    HentSøknaderErrors,
    HentSøknaderResponses,
    HentSøknadErrors,
    HentSøknadResponses,
    LastNedArbeidsgivermeldingData,
    LastNedArbeidsgivermeldingErrors,
    LastNedArbeidsgivermeldingResponses,
    OppdaterAktoerIdData,
    OppdaterAktoerIdErrors,
    OppdaterAktoerIdResponses,
} from './types.gen';
import {
    zAktiverMikrofrontendBody,
    zAktiverMikrofrontendResponse,
    zHentDokumentOversiktQuery,
    zHentDokumentOversiktResponse,
    zHentDokumentPath,
    zHentDokumentQuery,
    zHentDokumentResponse,
    zHentMikrofrontenderBody,
    zHentMikrofrontenderResponse,
    zHentSøknader1Response,
    zHentSøknaderResponse,
    zHentSøknadPath,
    zHentSøknadResponse,
    zLastNedArbeidsgivermeldingPath,
    zLastNedArbeidsgivermeldingQuery,
    zLastNedArbeidsgivermeldingResponse,
    zOppdaterAktoerIdBody,
    zOppdaterAktoerIdResponse,
} from './zod.gen';

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
    TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class DokumentController {
    public static hentDokumentOversikt<ThrowOnError extends boolean = true>(
        options: Options<HentDokumentOversiktData, ThrowOnError>,
    ) {
        return (options.client ?? client).get<HentDokumentOversiktResponses, HentDokumentOversiktErrors, ThrowOnError>({
            requestValidator: async (data) =>
                await z
                    .object({
                        body: z.never().optional(),
                        path: z.never().optional(),
                        query: zHentDokumentOversiktQuery,
                    })
                    .parseAsync(data),
            responseType: 'json',
            responseValidator: async (data) => await zHentDokumentOversiktResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/dokument/oversikt',
            ...options,
        });
    }

    public static hentDokument<ThrowOnError extends boolean = true>(options: Options<HentDokumentData, ThrowOnError>) {
        return (options.client ?? client).get<HentDokumentResponses, HentDokumentErrors, ThrowOnError>({
            requestValidator: async (data) =>
                await z
                    .object({
                        body: z.never().optional(),
                        path: zHentDokumentPath,
                        query: zHentDokumentQuery,
                    })
                    .parseAsync(data),
            responseType: 'blob',
            responseValidator: async (data) => await zHentDokumentResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/dokument/{journalpostId}/{dokumentInfoId}/{variantFormat}',
            ...options,
        });
    }
}

export class MikrofrontendForvaltningController {
    public static aktiverMikrofrontend<ThrowOnError extends boolean = true>(
        options: Options<AktiverMikrofrontendData, ThrowOnError>,
    ) {
        return (options.client ?? client).post<AktiverMikrofrontendResponses, AktiverMikrofrontendErrors, ThrowOnError>(
            {
                requestValidator: async (data) =>
                    await z
                        .object({
                            body: zAktiverMikrofrontendBody,
                            path: z.never().optional(),
                            query: z.never().optional(),
                        })
                        .parseAsync(data),
                responseType: 'json',
                responseValidator: async (data) => await zAktiverMikrofrontendResponse.parseAsync(data),
                security: [{ scheme: 'bearer', type: 'http' }],
                url: '/forvaltning/mikrofrontend/aktiver',
                ...options,
                headers: {
                    'Content-Type': 'application/json',
                    ...options.headers,
                },
            },
        );
    }

    public static hentMikrofrontender<ThrowOnError extends boolean = true>(
        options: Options<HentMikrofrontenderData, ThrowOnError>,
    ) {
        return (options.client ?? client).post<HentMikrofrontenderResponses, HentMikrofrontenderErrors, ThrowOnError>({
            requestValidator: async (data) =>
                await z
                    .object({
                        body: zHentMikrofrontenderBody,
                        path: z.never().optional(),
                        query: z.never().optional(),
                    })
                    .parseAsync(data),
            responseType: 'json',
            responseValidator: async (data) => await zHentMikrofrontenderResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/forvaltning/mikrofrontend/hent',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }
}

export class AktØrBytteController {
    public static oppdaterAktoerId<ThrowOnError extends boolean = true>(
        options: Options<OppdaterAktoerIdData, ThrowOnError>,
    ) {
        return (options.client ?? client).post<OppdaterAktoerIdResponses, OppdaterAktoerIdErrors, ThrowOnError>({
            requestValidator: async (data) =>
                await z
                    .object({
                        body: zOppdaterAktoerIdBody,
                        path: z.never().optional(),
                        query: z.never().optional(),
                    })
                    .parseAsync(data),
            responseType: 'json',
            responseValidator: async (data) => await zOppdaterAktoerIdResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/forvaltning/oppdaterAktoerId',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers,
            },
        });
    }
}

export class K9SakInnsynSØknadController {
    public static hentSøknader1<ThrowOnError extends boolean = true>(
        options?: Options<HentSøknader1Data, ThrowOnError>,
    ) {
        return (options?.client ?? client).get<HentSøknader1Responses, HentSøknader1Errors, ThrowOnError>({
            requestValidator: async (data) =>
                await z
                    .object({
                        body: z.never().optional(),
                        path: z.never().optional(),
                        query: z.never().optional(),
                    })
                    .parseAsync(data),
            responseType: 'json',
            responseValidator: async (data) => await zHentSøknader1Response.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/innsyn/sak',
            ...options,
        });
    }
}

export class SØknadController {
    public static hentSøknader<ThrowOnError extends boolean = true>(options?: Options<HentSøknaderData, ThrowOnError>) {
        return (options?.client ?? client).get<HentSøknaderResponses, HentSøknaderErrors, ThrowOnError>({
            requestValidator: async (data) =>
                await z
                    .object({
                        body: z.never().optional(),
                        path: z.never().optional(),
                        query: z.never().optional(),
                    })
                    .parseAsync(data),
            responseType: 'json',
            responseValidator: async (data) => await zHentSøknaderResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/soknad',
            ...options,
        });
    }

    public static hentSøknad<ThrowOnError extends boolean = true>(options: Options<HentSøknadData, ThrowOnError>) {
        return (options.client ?? client).get<HentSøknadResponses, HentSøknadErrors, ThrowOnError>({
            requestValidator: async (data) =>
                await z
                    .object({
                        body: z.never().optional(),
                        path: zHentSøknadPath,
                        query: z.never().optional(),
                    })
                    .parseAsync(data),
            responseType: 'json',
            responseValidator: async (data) => await zHentSøknadResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/soknad/{søknadId}',
            ...options,
        });
    }

    public static lastNedArbeidsgivermelding<ThrowOnError extends boolean = true>(
        options: Options<LastNedArbeidsgivermeldingData, ThrowOnError>,
    ) {
        return (options.client ?? client).get<
            LastNedArbeidsgivermeldingResponses,
            LastNedArbeidsgivermeldingErrors,
            ThrowOnError
        >({
            requestValidator: async (data) =>
                await z
                    .object({
                        body: z.never().optional(),
                        path: zLastNedArbeidsgivermeldingPath,
                        query: zLastNedArbeidsgivermeldingQuery,
                    })
                    .parseAsync(data),
            responseType: 'blob',
            responseValidator: async (data) => await zLastNedArbeidsgivermeldingResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/soknad/{søknadId}/arbeidsgivermelding',
            ...options,
        });
    }
}
