// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string & {};
};

export type Aktivitetspenger = Omit<Ytelse, 'type'> & {
    forutgåendeBosteder: Bosteder;
    inntekter?: OppgittInntekt;
    søknadsperiode: string;
    type: 'Aktivitetspenger';
};

export type AktørBytteRequest = {
    gyldigAktør: string;
    utgåttAktør: string;
};

export type AktørBytteRespons = {
    antallOppdaterteRader: number;
};

export type AnnenAktivitet = {
    annenAktivitetType: 'MILITÆR_ELLER_SIVILTJENESTE' | '-';
    periode: string;
};

export type AnnenForelder = {
    norskIdentitetsnummer: string;
    periode?: string;
    situasjon: 'INNLAGT_I_HELSEINSTITUSJON' | 'UTØVER_VERNEPLIKT' | 'FENGSEL' | 'SYKDOM' | 'ANNET';
    situasjonBeskrivelse?: string;
};

export type Arbeidstaker = {
    arbeidstidInfo: ArbeidstidInfo;
    norskIdentitetsnummer?: string;
    organisasjonsnavn?: string;
    organisasjonsnummer?: string;
};

export type Arbeidstid = {
    arbeidstakerList: Arbeidstaker[];
    frilanserArbeidstidInfo?: ArbeidstidInfo;
    selvstendigNæringsdrivendeArbeidstidInfo?: ArbeidstidInfo;
};

export type ArbeidstidInfo = {
    perioder: {
        [key: string]: ArbeidstidPeriodeInfo;
    };
};

export type ArbeidstidPeriodeInfo = {
    faktiskArbeidTimerPerDag: string;
    jobberNormaltTimerPerDag: string;
};

export type Barn = {
    fødselsdato?: string;
    norskIdentitetsnummer: string;
};

export type BarnOpplysninger = {
    aktørId: string;
    etternavn: string;
    fornavn: string;
    fødselsdato: string;
    identitetsnummer?: string;
    mellomnavn?: string;
};

export type BegrunnelseForInnsending = {
    tekst?: string;
};

export type Beredskap = {
    perioder: {
        [key: string]: BeredskapPeriodeInfo;
    };
    perioderSomSkalSlettes?: {
        [key: string]: BeredskapPeriodeInfo;
    };
};

export type BeredskapPeriodeInfo = {
    tilleggsinformasjon: string;
};

export type BostedPeriodeInfo = {
    land: string;
};

export type Bosteder = {
    perioder?: {
        [key: string]: BostedPeriodeInfo;
    };
};

export type DataBruktTilUtledning = {
    annetData?: string;
    harBekreftetOpplysninger: boolean;
    harForståttRettigheterOgPlikter: boolean;
    soknadDialogCommitSha?: string;
};

export type DelvisFravær = {
    fravær: string;
    normalarbeidstid: string;
};

export type DokumentDto = {
    dokumentInfoId: string;
    filtype: string;
    harTilgang: boolean;
    journalpostId: string;
    relevanteDatoer: RelevantDato[];
    sakId?: string;
    tittel: string;
    url: string;
};

export type FraværPeriode = {
    aktivitetFravær: Array<'ARBEIDSTAKER' | 'FRILANSER' | 'SELVSTENDIG_VIRKSOMHET'>;
    arbeidsforholdId?: string;
    arbeidsgiverOrgNr?: string;
    delvisFravær?: DelvisFravær;
    duration?: string;
    periode: string;
    søknadÅrsak?: 'ARBEIDSGIVER_KONKURS' | 'NYOPPSTARTET_HOS_ARBEIDSGIVER' | 'KONFLIKT_MED_ARBEIDSGIVER';
    årsak: 'STENGT_SKOLE_ELLER_BARNEHAGE' | 'SMITTEVERNHENSYN' | 'ORDINÆRT_FRAVÆR';
};

export type Frilanser = {
    sluttdato?: string;
    startdato: string;
};

export type InfoFraPunsj = {
    inneholderMedisinskeOpplysninger?: boolean;
    søknadenInneholderInfomasjonSomIkkeKanPunsjes?: boolean;
};

export type Journalpost = {
    /**
     * @deprecated
     */
    inneholderInfomasjonSomIkkeKanPunsjes: boolean;
    inneholderInformasjonSomIkkeKanPunsjes: boolean;
    inneholderMedisinskeOpplysninger: boolean;
    journalpostId: string;
};

export type K9SakInnsynSøknad = {
    barn: BarnOpplysninger;
    søknad: Søknad;
};

export type Kurs = {
    kursholder: Kursholder;
    kursperioder: string[];
    reise: Reise;
};

export type Kursholder = {
    institusjonsidentifikator?: string;
    navn?: string;
};

export type LovbestemtFerie = {
    perioder: {
        [key: string]: LovbestemtFeriePeriodeInfo;
    };
};

export type LovbestemtFeriePeriodeInfo = {
    skalHaFerie?: boolean;
};

export type MikrofrontendAktiverRequest = {
    fødselsnummer: string;
};

export type MikrofrontendOppslagRequest = {
    fødselsnummer: string;
};

export type MikrofrontendRespons = {
    behandlingsdato?: string;
    endret?: string;
    fødselsnummer: string;
    id: string;
    mikrofrontendId: string;
    opprettet?: string;
    status: 'ENABLE' | 'DISABLE';
};

export type Nattevåk = {
    perioder: {
        [key: string]: NattevåkPeriodeInfo;
    };
    perioderSomSkalSlettes: {
        [key: string]: NattevåkPeriodeInfo;
    };
};

export type NattevåkPeriodeInfo = {
    tilleggsinformasjon: string;
};

export type Omsorg = {
    beskrivelseAvOmsorgsrollen?: string;
    relasjonTilBarnet?: 'MOR' | 'MEDMOR' | 'FAR' | 'FOSTERFORELDER' | 'ANNET';
};

export type OmsorgspengerAleneOmsorg = Omit<Ytelse, 'type'> & {
    barn: Barn;
    dataBruktTilUtledning?: DataBruktTilUtledning;
    periode: string;
    type: 'OmsorgspengerAleneOmsorg';
};

export type OmsorgspengerKroniskSyktBarn = Omit<Ytelse, 'type'> & {
    barn: Barn;
    dataBruktTilUtledning?: DataBruktTilUtledning;
    høyereRisikoForFravær?: boolean;
    høyereRisikoForFraværBeskrivelse?: string;
    kroniskEllerFunksjonshemming: boolean;
    type: 'OmsorgspengerKroniskSyktBarn';
};

export type OmsorgspengerMidlertidigAlene = Omit<Ytelse, 'type'> & {
    annenForelder: AnnenForelder;
    barn: Barn[];
    begrunnelse?: string;
    dataBruktTilUtledning?: DataBruktTilUtledning;
    type: 'OmsorgspengerMidlertidigAlene';
};

export type OmsorgspengerUtbetaling = Omit<Ytelse, 'type'> & {
    aktivitet?: OpptjeningAktivitet;
    bosteder?: Bosteder;
    dataBruktTilUtledning?: DataBruktTilUtledning;
    fosterbarn?: Barn[];
    fraværsperioder?: FraværPeriode[];
    fraværsperioderKorrigeringIm?: FraværPeriode[];
    utenlandsopphold?: Utenlandsopphold;
    type: 'OmsorgspengerUtbetaling';
};

export type OppgittInntekt = {
    oppgittePeriodeinntekter: OppgittInntektForPeriode[];
};

export type OppgittInntektForPeriode = {
    arbeidstakerOgFrilansInntekt?: number;
    næringsinntekt?: number;
    periode: string;
    ytelse?: number;
};

export type Opplæringspenger = Omit<Ytelse, 'type'> & {
    arbeidstid: Arbeidstid;
    barn: Barn;
    bosteder: Bosteder;
    dataBruktTilUtledning?: DataBruktTilUtledning;
    kurs?: Kurs;
    lovbestemtFerie: LovbestemtFerie;
    omsorg: Omsorg;
    opptjeningAktivitet: OpptjeningAktivitet;
    skalEttersendeVedlegg?: boolean;
    søknadsperiode: string[];
    trekkKravPerioder: string[];
    utenlandsopphold: Utenlandsopphold;
    uttak: Uttak;
    type: 'Opplæringspenger';
};

export type OpptjeningAktivitet = {
    andreAktiviteter: AnnenAktivitet[];
    frilanser?: Frilanser;
    selvstendigNæringsdrivende: SelvstendigNæringsdrivende[];
    utenlandskeArbeidsforhold: UtenlandskArbeidsforhold[];
};

export type PleiepengerSyktBarn = Omit<Ytelse, 'type'> & {
    annetDataBruktTilUtledning?: DataBruktTilUtledning;
    arbeidstid: Arbeidstid;
    barn: Barn;
    beredskap: Beredskap;
    bosteder: Bosteder;
    dataBruktTilUtledning?: DataBruktTilUtledning;
    /**
     * @deprecated
     */
    endringsperiode: string[];
    erSammenMedBarnet?: boolean;
    /**
     * @deprecated
     */
    infoFraPunsj?: InfoFraPunsj;
    lovbestemtFerie: LovbestemtFerie;
    nattevåk: Nattevåk;
    omsorg: Omsorg;
    opptjeningAktivitet?: OpptjeningAktivitet;
    søknadsperiode: string[];
    tilsynsordning: Tilsynsordning;
    trekkKravPerioder: string[];
    utenlandsopphold: Utenlandsopphold;
    uttak: Uttak;
    type: 'PleiepengerSyktBarn';
};

export type Pleietrengende = {
    fødselsdato?: string;
    norskIdentitetsnummer?: string;
};

export type PleipengerLivetsSluttfase = Omit<Ytelse, 'type'> & {
    arbeidstid: Arbeidstid;
    bosteder: Bosteder;
    dataBruktTilUtledning?: DataBruktTilUtledning;
    lovbestemtFerie?: LovbestemtFerie;
    opptjeningAktivitet?: OpptjeningAktivitet;
    pleietrengende: Pleietrengende;
    søknadsperiode: string[];
    trekkKravPerioder: string[];
    utenlandsopphold: Utenlandsopphold;
    uttak?: Uttak;
    type: 'PleipengerLivetsSluttfase';
};

export type ProblemDetail = {
    detail?: string;
    instance?: string;
    properties?: {
        [key: string]: unknown;
    };
    status?: number;
    title?: string;
    type?: string;
};

export type Reise = {
    reisedager?: string[];
    reisedagerBeskrivelse?: string;
    reiserUtenforKursdager: boolean;
};

export type RelevantDato = {
    dato: string;
    datotype:
        | 'DATO_OPPRETTET'
        | 'DATO_SENDT_PRINT'
        | 'DATO_EKSPEDERT'
        | 'DATO_JOURNALFOERT'
        | 'DATO_REGISTRERT'
        | 'DATO_AVS_RETUR'
        | 'DATO_DOKUMENT'
        | '__UNKNOWN_VALUE';
};

export type SelvstendigNæringsdrivende = {
    organisasjonsnummer?: string;
    perioder: {
        [key: string]: SelvstendigNæringsdrivendePeriodeInfo;
    };
    virksomhetNavn?: string;
};

export type SelvstendigNæringsdrivendePeriodeInfo = {
    bruttoInntekt?: number;
    endringBegrunnelse?: string;
    endringDato?: string;
    erFiskerPåBladB?: boolean;
    erNyIArbeidslivet?: boolean;
    erNyoppstartet?: boolean;
    erVarigEndring?: boolean;
    landkode?: string;
    registrertIUtlandet?: boolean;
    regnskapsførerNavn?: string;
    regnskapsførerTlf?: string;
    virksomhetstyper: Array<'DAGMAMMA' | 'FISKE' | 'JORDBRUK_SKOGBRUK' | 'ANNEN' | '-'>;
};

export type Søker = {
    norskIdentitetsnummer: string;
};

export type Søknad = {
    begrunnelseForInnsending?: BegrunnelseForInnsending;
    journalposter?: Journalpost[];
    kildesystem?: string;
    mottattDato: string;
    språk?: 'nb' | 'nn';
    søker: Søker;
    søknadId: string;
    versjon: string;
    ytelse:
        | Aktivitetspenger
        | OmsorgspengerAleneOmsorg
        | OmsorgspengerKroniskSyktBarn
        | OmsorgspengerMidlertidigAlene
        | OmsorgspengerUtbetaling
        | Opplæringspenger
        | PleiepengerSyktBarn
        | PleipengerLivetsSluttfase
        | Ungdomsytelse;
};

export type SøknadDto = {
    behandlingsdato?: string;
    dokumenter: DokumentDto[];
    endret?: string;
    journalpostId: string;
    opprettet?: string;
    saksId?: string;
    status: 'MOTTATT' | 'UNDER_BEHANDLING' | 'FERDIG_BEHANDLET';
    søknad: {
        [key: string]: unknown;
    };
    søknadId: string;
    søknadstype:
        | 'PP_SYKT_BARN'
        | 'PP_ETTERSENDELSE'
        | 'PP_LIVETS_SLUTTFASE_ETTERSENDELSE'
        | 'OMS_ETTERSENDELSE'
        | 'PP_SYKT_BARN_ENDRINGSMELDING';
};

export type TilsynPeriodeInfo = {
    etablertTilsynTimerPerDag: string;
};

export type Tilsynsordning = {
    perioder: {
        [key: string]: TilsynPeriodeInfo;
    };
};

export type Ungdomsytelse = Omit<Ytelse, 'type'> & {
    deltakelseId?: string;
    inntekter?: OppgittInntekt;
    søknadType: 'DELTAKELSE_SØKNAD' | 'RAPPORTERING_SØKNAD';
    søktFraDatoer: string[];
    type: 'Ungdomsytelse';
};

export type UtenlandskArbeidsforhold = {
    ansettelsePeriode: string;
    arbeidsgiversnavn: string;
    land: string;
};

export type Utenlandsopphold = {
    perioder?: {
        [key: string]: UtenlandsoppholdPeriodeInfo;
    };
    perioderSomSkalSlettes?: {
        [key: string]: UtenlandsoppholdPeriodeInfo;
    };
};

export type UtenlandsoppholdPeriodeInfo = {
    erSammenMedBarnet?: boolean;
    land: string;
    årsak?:
        | 'barnetInnlagtIHelseinstitusjonForNorskOffentligRegning'
        | 'barnetInnlagtIHelseinstitusjonDekketEtterAvtaleMedEtAnnetLandOmTrygd';
};

export type Uttak = {
    perioder: {
        [key: string]: UttakPeriodeInfo;
    };
};

export type UttakPeriodeInfo = {
    timerPleieAvBarnetPerDag: string;
};

export type Ytelse = {
    type: string;
};

export type FraværPeriodeWritable = {
    aktivitetFravær: Array<'ARBEIDSTAKER' | 'FRILANSER' | 'SELVSTENDIG_VIRKSOMHET'>;
    arbeidsforholdId?: string;
    arbeidsgiverOrgNr?: string;
    delvisFravær?: DelvisFravær;
    duration?: string;
    organisasjonsnummer?: string;
    periode: string;
    søknadÅrsak?: 'ARBEIDSGIVER_KONKURS' | 'NYOPPSTARTET_HOS_ARBEIDSGIVER' | 'KONFLIKT_MED_ARBEIDSGIVER';
    årsak: 'STENGT_SKOLE_ELLER_BARNEHAGE' | 'SMITTEVERNHENSYN' | 'ORDINÆRT_FRAVÆR';
};

export type K9SakInnsynSøknadWritable = {
    barn: BarnOpplysninger;
    søknad: SøknadWritable;
};

export type OmsorgspengerUtbetalingWritable = Omit<Ytelse, 'type'> & {
    aktivitet?: OpptjeningAktivitet;
    bosteder?: Bosteder;
    dataBruktTilUtledning?: DataBruktTilUtledning;
    fosterbarn?: Barn[];
    fraværsperioder?: FraværPeriodeWritable[];
    fraværsperioderKorrigeringIm?: FraværPeriodeWritable[];
    utenlandsopphold?: Utenlandsopphold;
    type: 'OmsorgspengerUtbetalingWritable';
};

export type SøknadWritable = {
    begrunnelseForInnsending?: BegrunnelseForInnsending;
    journalposter?: Journalpost[];
    kildesystem?: string;
    mottattDato: string;
    språk?: 'nb' | 'nn';
    søker: Søker;
    søknadId: string;
    versjon: string;
    ytelse:
        | Aktivitetspenger
        | OmsorgspengerAleneOmsorg
        | OmsorgspengerKroniskSyktBarn
        | OmsorgspengerMidlertidigAlene
        | OmsorgspengerUtbetalingWritable
        | Opplæringspenger
        | PleiepengerSyktBarn
        | PleipengerLivetsSluttfase
        | Ungdomsytelse;
};

export type HentDokumentOversiktData = {
    body?: never;
    path?: never;
    query: {
        brevkoder: string[];
    };
    url: '/dokument/oversikt';
};

export type HentDokumentOversiktErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetail;
    /**
     * Unauthorized
     */
    401: ProblemDetail;
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type HentDokumentOversiktError = HentDokumentOversiktErrors[keyof HentDokumentOversiktErrors];

export type HentDokumentOversiktResponses = {
    /**
     * OK
     */
    200: DokumentDto[];
};

export type HentDokumentOversiktResponse = HentDokumentOversiktResponses[keyof HentDokumentOversiktResponses];

export type HentDokumentData = {
    body?: never;
    path: {
        journalpostId: string;
        dokumentInfoId: string;
        variantFormat: string;
    };
    query: {
        dokumentTittel: string;
    };
    url: '/dokument/{journalpostId}/{dokumentInfoId}/{variantFormat}';
};

export type HentDokumentErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetail;
    /**
     * Unauthorized
     */
    401: ProblemDetail;
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type HentDokumentError = HentDokumentErrors[keyof HentDokumentErrors];

export type HentDokumentResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type HentDokumentResponse = HentDokumentResponses[keyof HentDokumentResponses];

export type AktiverMikrofrontendData = {
    body: MikrofrontendAktiverRequest;
    path?: never;
    query?: never;
    url: '/forvaltning/mikrofrontend/aktiver';
};

export type AktiverMikrofrontendErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetail;
    /**
     * Unauthorized
     */
    401: ProblemDetail;
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type AktiverMikrofrontendError = AktiverMikrofrontendErrors[keyof AktiverMikrofrontendErrors];

export type AktiverMikrofrontendResponses = {
    /**
     * OK
     */
    200: MikrofrontendRespons;
};

export type AktiverMikrofrontendResponse = AktiverMikrofrontendResponses[keyof AktiverMikrofrontendResponses];

export type HentMikrofrontenderData = {
    body: MikrofrontendOppslagRequest;
    path?: never;
    query?: never;
    url: '/forvaltning/mikrofrontend/hent';
};

export type HentMikrofrontenderErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetail;
    /**
     * Unauthorized
     */
    401: ProblemDetail;
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type HentMikrofrontenderError = HentMikrofrontenderErrors[keyof HentMikrofrontenderErrors];

export type HentMikrofrontenderResponses = {
    /**
     * OK
     */
    200: MikrofrontendRespons[];
};

export type HentMikrofrontenderResponse = HentMikrofrontenderResponses[keyof HentMikrofrontenderResponses];

export type OppdaterAktoerIdData = {
    body: AktørBytteRequest;
    path?: never;
    query?: never;
    url: '/forvaltning/oppdaterAktoerId';
};

export type OppdaterAktoerIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetail;
    /**
     * Unauthorized
     */
    401: ProblemDetail;
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type OppdaterAktoerIdError = OppdaterAktoerIdErrors[keyof OppdaterAktoerIdErrors];

export type OppdaterAktoerIdResponses = {
    /**
     * OK
     */
    200: AktørBytteRespons;
};

export type OppdaterAktoerIdResponse = OppdaterAktoerIdResponses[keyof OppdaterAktoerIdResponses];

export type HentSøknader1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/innsyn/sak';
};

export type HentSøknader1Errors = {
    /**
     * Bad Request
     */
    400: ProblemDetail;
    /**
     * Unauthorized
     */
    401: ProblemDetail;
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type HentSøknader1Error = HentSøknader1Errors[keyof HentSøknader1Errors];

export type HentSøknader1Responses = {
    /**
     * OK
     */
    200: K9SakInnsynSøknad[];
};

export type HentSøknader1Response = HentSøknader1Responses[keyof HentSøknader1Responses];

export type HentSøknaderData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/soknad';
};

export type HentSøknaderErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetail;
    /**
     * Unauthorized
     */
    401: ProblemDetail;
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type HentSøknaderError = HentSøknaderErrors[keyof HentSøknaderErrors];

export type HentSøknaderResponses = {
    /**
     * OK
     */
    200: SøknadDto[];
};

export type HentSøknaderResponse = HentSøknaderResponses[keyof HentSøknaderResponses];

export type HentSøknadData = {
    body?: never;
    path: {
        søknadId: string;
    };
    query?: never;
    url: '/soknad/{søknadId}';
};

export type HentSøknadErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetail;
    /**
     * Unauthorized
     */
    401: ProblemDetail;
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type HentSøknadError = HentSøknadErrors[keyof HentSøknadErrors];

export type HentSøknadResponses = {
    /**
     * OK
     */
    200: SøknadDto;
};

export type HentSøknadResponse = HentSøknadResponses[keyof HentSøknadResponses];

export type LastNedArbeidsgivermeldingData = {
    body?: never;
    path: {
        søknadId: string;
    };
    query: {
        organisasjonsnummer: string;
    };
    url: '/soknad/{søknadId}/arbeidsgivermelding';
};

export type LastNedArbeidsgivermeldingErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetail;
    /**
     * Unauthorized
     */
    401: ProblemDetail;
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type LastNedArbeidsgivermeldingError = LastNedArbeidsgivermeldingErrors[keyof LastNedArbeidsgivermeldingErrors];

export type LastNedArbeidsgivermeldingResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type LastNedArbeidsgivermeldingResponse =
    LastNedArbeidsgivermeldingResponses[keyof LastNedArbeidsgivermeldingResponses];
